In [56]:
import torch
import schnetpack as spk
import math
from schnetpack.datasets import QM9


import numpy as np
from numpy import savetxt

In [57]:
def hydrogen_nbh_matrix(number_atoms,atom_numb,x,y,z):
    #Returns the connections to the hydrogens
    count_H = 0
    for i in range(number_atoms):
        if atom_numb[i] == 1:
            count_H = count_H + 1
            
    hydrogen_nbh_distx = np.zeros((count_H,number_atoms))
    hydrogen_nbh_disty = np.zeros((count_H,number_atoms))
    hydrogen_nbh_distz = np.zeros((count_H,number_atoms))
    hydrogen_nbh_distance = np.zeros((count_H,number_atoms))
    
    count_H=0
    for i in range(number_atoms):
        if atom_numb[i] == 1:
            for j in range(number_atoms):
                hydrogen_nbh_distx[count_H][j] = x[i] - x[j]
                hydrogen_nbh_disty[count_H][j] = y[i] - y[j]
                hydrogen_nbh_distz[count_H][j] = z[i] - z[j]
                hydrogen_nbh_distance[count_H][j] = math.sqrt(hydrogen_nbh_distx[count_H][j]**2 + hydrogen_nbh_distx[count_H][j]**2 + hydrogen_nbh_distx[count_H][j]**2)
            count_H=count_H+1
    
    nbh_idx=np.zeros((count_H))
    for i in range(count_H):
        nbh_next_shortest = hydrogen_nbh_distance[i][0] 
        nbh_next_minimum = 0
        for j in range(number_atoms):
            if nbh_next_minimum < nbh_next_shortest < hydrogen_nbh_distance[i][j] and atom_numb[j]!=1:
                nbh_next_shortest = hydrogen_nbh_distance[i][j]
                nbh_next_minimum = hydrogen_nbh_distance[i][j]
                nbh_idx[i] = j
            
    print(hydrogen_nbh_distance)
    return nbh_idx
            


    
def Neighbors_Regression(num_mol):
    
    from schnetpack.datasets import QM9

    qm9data = QM9('./qm9.db', download=True, remove_uncharacterized=True)

    for idx in range(num_mol):
        
        ##Loading important data, converting tensors to numpy arrays 
        at, props = qm9data.get_properties(idx)
        x = props['_positions'][ :,0]
        y = props['_positions'][ :,1]
        z = props['_positions'][ :,2] 
    
        x=x.detach().numpy()
        y=y.detach().numpy()
        z=z.detach().numpy()
        
        number_atoms = len(z)
        
        atom_numb = props['_atomic_numbers']
        
        atom_numb = atom_numb.detach().numpy()
        
        nbh_idx = hydrogen_nbh_matrix(number_atoms,atom_numb,x,y,z)
        
        
        
        
        
        



In [58]:
num_mol = 20

Neighbors_Regression(num_mol)



[[0.02571845 0.         1.7486445  0.94044378 0.91099641]
 [1.77436301 1.7486445  0.         2.68908818 2.65964091]
 [0.91472527 0.94044378 2.68908818 0.         0.02944738]
 [0.8852779  0.91099641 2.65964091 0.02944738 0.        ]]
[[0.09991077 0.         1.55630293 0.93103826]
 [1.65621373 1.55630293 0.         2.48734119]
 [0.83112746 0.93103826 2.48734119 0.        ]]
[[0.17169297 0.         1.39780637]
 [1.56949926 1.39780637 0.        ]]
[[3.91647521 1.8396096  0.         5.75608502]
 [1.8396096  3.91647521 5.75608502 0.        ]]
[[0.02507796 0.05215797 0.        ]]
[[1.60896776 1.58074975 0.         3.24598433]
 [1.63701667 1.66523469 3.24598433 0.        ]]
[[1.75556642 1.71952635 0.         2.66207362 2.63291459 0.81300078
  3.47509856 0.84220369]
 [0.90650709 0.94254716 2.66207362 0.         0.02915903 1.84907263
  0.81302525 1.81986983]
 [0.87734806 0.91338813 2.63291459 0.02915903 0.         1.8199136
  0.84218428 1.79071079]
 [0.94256564 0.90652557 0.81300078 1.84907263 1