Label converter: converts from LDA labels to gnuplot colors

In [12]:
import numpy as np
from numpy import genfromtxt, savetxt

label_filepath = '../data/eucdist/pkaeucdist/pk1wlabels.csv'
pka_label = genfromtxt(label_filepath,delimiter=',',encoding='utf-8-sig')

label_data = pka_label[:,1]

lda_to_gnu_converter_dictionary = {
    0:  [16711680,13],
    1:  [16747520,7],
    2:  [16776960,11],
    3:  [6737322,1],
    4:  [3978097,15],
    5:  [10025880,9],
    6:  [10025880,9],
    7:  [11393254,2],
    8:  [6266528,5],
    9:  [8900346,13],
    10: [4286945,13],
    11: [6591981,3],
    12: [15787660,7],
    13: [16766720,5],
    14: [11674146,15],
    15: [16758465,11],
    16: [16770273,1],
    17: [16716947,3],
    18: [16738740,15],
    19: [16716947,3],
    20: [14524637,5],
    21: [8388736,5],
    22: [14381203,9],
    23: [16738740,7],
    24: [10824234,7],
    25: [12433259,13],
    26: [4915330,3],
    27: [13468991,9],
    28: [5597999,7],
    29: [9127187,5],
}


In [13]:

new_label = []
for each_label in range(len(label_data)):
    
    new_label.append(lda_to_gnu_converter_dictionary[label_data[each_label]])
    

In [14]:
new_label = np.asarray(new_label)

new_label = np.hstack((pka_label,new_label))


In [15]:
print(new_label)

savetxt('test.csv',new_label,delimiter=',')

[[1.3270000e+01 1.4000000e+01 1.1674146e+07 1.5000000e+01]
 [3.7370000e+00 2.9000000e+01 9.1271870e+06 5.0000000e+00]
 [1.5500000e+01 5.0000000e+00 1.0025880e+07 9.0000000e+00]
 ...
 [4.4200000e+00 8.0000000e+00 6.2665280e+06 5.0000000e+00]
 [4.7000000e+00 8.0000000e+00 6.2665280e+06 5.0000000e+00]
 [4.2100000e+00 8.0000000e+00 6.2665280e+06 5.0000000e+00]]
