In [15]:
import os
import fileinput
from schnetpack.datasets import QM9
import numpy as np
import pandas as pd
from xlwt import Workbook
from numpy import savetxt

#Load qm9data
qm9data = QM9('./qm9.db', download=True, remove_uncharacterized=True)

#Input range of QM9 to be labelled
print('how many QM9 molecules do you want to label?')
#number_of_molecules = input()
#number_of_molecules = int(number_of_molecules)

how many QM9 molecules do you want to label?


In [16]:
def get_coordinates(props):
    x = props['_positions'][ :,0]
    y = props['_positions'][ :,1]
    z = props['_positions'][ :,2]
    x = x.numpy()
    y = y.numpy()
    z = z.numpy()
    return x, y, z

def write_coordinates_xyz(name_xyz,props):    
    x = get_coordinates(props)[0]
    y = get_coordinates(props)[1]
    z = get_coordinates(props)[2] 
    file_xyz = open(name_xyz, mode='w',encoding='utf-8')
    
    number_of_atoms = len(z)
    number_of_atoms = int(number_of_atoms)
    file_xyz.write(str(len(z))+'\n')    
    file_xyz.write('title'+'\n')
    for i in range(number_of_atoms):
        if props['_atomic_numbers'][i] == 1:
            string = ('H' + ' ' +  str(x[i]) + ' ' + str(y[i]) + ' ' + str(z[i]) + '\n')
            file_xyz.write(string)
        if props['_atomic_numbers'][i] == 6:
            string = ('C' + ' ' +  str(x[i]) + ' ' + str(y[i]) + ' ' + str(z[i]) + '\n')
            file_xyz.write(string)
        if props['_atomic_numbers'][i] == 8:
            string = ('O' + ' ' +  str(x[i]) + ' ' + str(y[i]) + ' ' + str(z[i]) + '\n')
            file_xyz.write(string)
        if props['_atomic_numbers'][i] == 7:
            string = ('N' + ' ' +  str(x[i]) + ' ' + str(y[i]) + ' ' + str(z[i]) + '\n')
            file_xyz.write(string)
        if props['_atomic_numbers'][i] == 9:
            string = ('F' + ' ' +  str(x[i]) + ' ' + str(y[i]) + ' ' + str(z[i]) + '\n')
            file_xyz.write(string)
    file_xyz.close()

def store_positions(name_mol,element,idx):
    countmollines = 0
    array_of_element = []
    for line in fileinput.FileInput(name_mol,inplace=0):
        countmollines = countmollines + 1
        if element in line:
            array_of_element.append([])
            array_of_element[len(array_of_element)-1] = int(countmollines-4)
    return array_of_element

def connection_matrix(name_mol,array_of_element,number_atoms):
    count=0
    connected_positions = []
    array = []
    for j in range(len(array_of_element)):
        connected_positions.append([])
        array.append([])
        array[j] = str(array_of_element[j])
    for line in fileinput.FileInput(name_mol,inplace=0):
        count = count + 1
        if count >= number_atoms + 5:
            line = line.replace(line,line[:7])
            for j in range(len(array_of_element)):
                if ' ' + str(array_of_element[j]) + ' ' in line and 'RAD' not in line:
                    connected_positions[j].append([])
                    if str(line[1]+line[2]+line[3]) == ' '+array[j]+' ' or str(line[0]+line[1]+line[2]+line[3]) == ' '+array[j]+' ':
                        connected = str(line[4:6])
                        connected = int(connected)
                        connected_positions[j][len(connected_positions[j])-1]=connected
                    else:
                        connected = str(line[1]+line[2]+line[3])
                        connected = int(connected)
                        connected_positions[j][len(connected_positions[j])-1]=connected
#    print(connected_positions)
    return connected_positions

def neighboring_connections(name_mol,carbon_position,number_atoms):
    carbon_neighbor_connections = []
    countmollines = 0
    for line in fileinput.FileInput(name_mol,inplace=0):
        countmollines = countmollines + 1
        if countmollines >= number_atoms + 5:
            line = line.replace(line,line[:7])
            if ' ' + str(carbon_position) + ' ' in line and 'RAD' not in line:
                carbon_neighbor_connections.append([])
                if str(line[1]+line[2]+line[3]) != ' ' + str(carbon_position) + ' ':
                    connected = str(line[1]+line[2]+line[3])
                    connected = int(connected)
                    carbon_neighbor_connections[len(carbon_neighbor_connections)-1]=connected
                else:
                    connected = str(line[4]+line[5]+line[6])
                    connected = int(connected)
                    carbon_neighbor_connections[len(carbon_neighbor_connections)-1]=connected
    return carbon_neighbor_connections
                    

In [17]:
# Store an array of all oxygen positions in each molecules
data = np.zeros((1,2))
for idx in range(100):
    at, props = qm9data.get_properties(idx)
    
    print(idx)
    name_xyz = '../data/label/5000/' + str(idx) + '.xyz'
    name_mol = '../data/label/5000/' + str(idx) + '.mol'
    
    #write coordinates xyz file
    write_coordinates_xyz(name_xyz,props)
    
    
    #convert xyz file to mol file using obabel
    os.system('obabel ' + name_xyz + ' -O ' + name_mol)
    

    element = ' O  '
    array_of_element = store_positions(name_mol,element,idx)
    print(array_of_element)
    
    x = get_coordinates(props)[0]
    number_atoms = len(x)
    
    # construct the matrix of connection
    if 8 in props['_atomic_numbers']:
        positions = array_of_element
        connected_positions = connection_matrix(name_mol,positions,number_atoms)
        print(connected_positions)
        
        ##Initialize important data holders 
        countC = np.zeros((len(connected_positions)))
        countH = np.zeros((len(connected_positions)))
        group = np.zeros((len(connected_positions)))
        label = np.zeros((len(connected_positions)))
        
        for j in range(len(connected_positions)):
            for i in range(len(connected_positions[j])):
                countxyzlines=0
                for line2 in fileinput.FileInput(name_xyz,inplace=0):
                    countxyzlines = countxyzlines+1
                    if countxyzlines == connected_positions[j][i]+2:
                        if 'C ' in line2:
                            countC[j] = countC[j]+1
                        if 'H ' in line2:
                            countH[j] = countH[j]+1
                            
        #label between alcohol/carbonyl/ether
        
            if countH[j] > 0:
                group[j] = 1.0
            elif countC[j] > 0 and countH[j] == 0:
                if countC[j] == 1:
                    group[j] = 2.0
                if countC[j] == 2:
                    label[j] = 1
                    

            if countH[j] > 0:
                if connected_positions[j][0] < connected_positions[j][1]:
                    connected_positions[j][0] = connected_positions[j][0]
                else:
                    connected_positions[j][0] = connected_positions[j][1]
           
            carbon_position = connected_positions[j][0]        

            
            if group[j] == 2.0:
                countC1 = np.zeros((len(connected_positions)))
                countO1 = np.zeros((len(connected_positions)))
                countH1 = np.zeros((len(connected_positions)))
                countN1 = np.zeros((len(connected_positions)))
                carbon_neighbor_connections = neighboring_connections(name_mol,carbon_position,number_atoms)
                for i in range(len(carbon_neighbor_connections)):
                    countxyzlines = 0
                    for line2 in fileinput.FileInput(name_xyz,inplace=0):
                        countxyzlines = countxyzlines + 1
                        if countxyzlines == carbon_neighbor_connections[i] + 2:
                            if 'C ' in line2:
                                countC1[j] = countC1[j] + 1
                            if 'H ' in line2:
                                countH1[j] = countH1[j] + 1
                            if 'N ' in line2:
                                countN1[j] = countN1[j] + 1
                            if 'O ' in line2:
                                countO1[j] = countO1[j] +1
                
                if countH1[j] == 2 and countC1[j] == 0:
                    label[j] = 2
                elif countC1[j] == 1 and countO1[j] ==1 and countH1[j] > 0 and countN1[j] ==0:
                    label[j] = 2
                elif countC1[j] == 2:
                    label[j] = 3
                elif countO1[j] > 1:
                    label[j] = 4
                elif countN1[j] > 0:
                    label[j] = 5
                else:
                    label[j] = 6
                
            
            
        
            if group[j] == 1.0:
                countC2 = np.zeros((len(connected_positions)))
                countH2 = np.zeros((len(connected_positions)))
                countO2 = np.zeros((len(connected_positions)))
                countN2 = np.zeros((len(connected_positions)))
                carbon_neighbor_connections = neighboring_connections(name_mol,carbon_position,number_atoms)
                for i in range(len(carbon_neighbor_connections)):
                    countxyzlines = 0
                    for line2 in fileinput.FileInput(name_xyz,inplace=0):
                        countxyzlines = countxyzlines + 1
                        if countxyzlines == carbon_neighbor_connections[i] + 2:
                            if 'C ' in line2:
                                countC2[j] = countC2[j] + 1
                            if 'H ' in line2:
                                countH2[j] = countH2[j] + 1
                            if 'N ' in line2:
                                countN2[j] = countN2[j] + 1
                            if 'O ' in line2:
                                countO2[j] = countO2[j] + 1
                if countC[j] == 0:
                    label[j] = 7
                elif countC2[j] + countN2[j] + countO2[j] == 2:
                    label[j] = 7
                elif countH2[j] == 2 or countH2[j] == 3:  
                    label[j]=7
                elif countC2[j] + countN2[j] + countO2[j] == 3:
                    label[j] = 8
                elif countC2[j] + countN2[j] + countO2[j] == 4:
                    label[j] = 9
                else:
                    label[j] = 6
                print(countC2[j])
                print(countH2[j])
                print(countN2[j])
                print(countO2[j])
                print(label[j])
                
                dt = np.array([[label[j], idx]])
    
                data = np.vstack((data,dt))
                                 
savetxt('../data/label/5000/label-o.csv',data,delimiter=',')
os.system('rm ../data/label/5000/*mol')
os.system('rm ../data/label/5000/*xyz')
            
                               
                
                
    
    
    
    
#    element = ' H  '
#    store_positions(name_mol,element,idx)
    

0
[]
1
[]
2
[1]
[[2, 3]]
0.0
0.0
0.0
1.0
7.0
3
[]
4
[]
5
[2]
[[1]]
6
[]
7
[2]
[[1, 6]]
0.0
3.0
0.0
1.0
7.0
8
[]
9
[]
10
[3]
[[2]]
11
[3]
[[2]]
12
[]
13
[3]
[[2, 9]]
1.0
2.0
0.0
1.0
7.0
14
[2]
[[1, 3]]
15
[]
16
[3]
[[2, 1]]
17
[4]
[[2]]
18
[4]
[[2]]
19
[4]
[[2]]
20
[]
21
[4]
[[2, 12]]
2.0
1.0
0.0
1.0
8.0
22
[]
23
[]
24
[]
25
[1]
[[2]]
26
[1]
[[2]]
27
[1, 4]
[[2], [3]]
28
[]
29
[]
30
[]
31
[]
32
[1]
[[2, 5]]
1.0
2.0
0.0
1.0
7.0
33
[1]
[[2, 5]]
1.0
2.0
0.0
1.0
7.0
34
[4]
[[3]]
35
[4]
[[3]]
36
[2, 4]
[[1, 3], [3]]
37
[1, 4]
[[2, 5], [3]]
1.0
2.0
0.0
1.0
7.0
38
[]
39
[4]
[[12, 3]]
1.0
2.0
0.0
1.0
7.0
40
[3]
[[2, 4]]
41
[1, 4]
[[2, 5], [10, 3]]
1.0
2.0
0.0
1.0
7.0
1.0
2.0
0.0
1.0
7.0
42
[]
43
[4]
[[2, 3]]
44
[]
45
[1]
[[2, 5]]
2.0
1.0
0.0
1.0
8.0
46
[]
47
[3]
[[2, 4]]
48
[5]
[[4, 12]]
1.0
0.0
0.0
1.0
7.0
49
[]
50
[]
51
[1]
[[2, 5]]
52
[1]
[[2, 5]]
53
[]
54
[5]
[[2, 15]]
3.0
0.0
0.0
1.0
9.0
55
[3]
[[2]]
56
[3]
[[2]]
57
[3]
[[2]]
58
[3, 5]
[[2], [4]]
59
[3, 5]
[[2], [4]]
60
[]
61
[]
62
[]
63
[

0

In [19]:
wb2 = Workbook()
sheet2 = wb2.add_sheet('Sheet1')
row=0

datah = np.zeros((1,2))
# Store an array of all oxygen positions in each molecules
for idx in range(5000):
    at, props = qm9data.get_properties(idx)
    
    print(idx)
    name_xyz = '../data/label/5000/' + str(idx) + '.xyz'
    name_mol = '../data/label/5000/' + str(idx) + '.mol'
    
    #write coordinates xyz file
    write_coordinates_xyz(name_xyz,props)
    
    
    #convert xyz file to mol file using obabel
    os.system('obabel ' + name_xyz + ' -O ' + name_mol)
    

    element = ' H  '
    array_of_element = store_positions(name_mol,element,idx)
    
    x = get_coordinates(props)[0]
    number_atoms = len(x)
    
    # construct the matrix of connection
    if 1 in props['_atomic_numbers']:
        positions = array_of_element
        connected_positions = connection_matrix(name_mol,positions,number_atoms)
        
        ##Initialize important data holders 
        countC = np.zeros((len(connected_positions)))
        countH = np.zeros((len(connected_positions)))
        countO = np.zeros((len(connected_positions)))
        countN = np.zeros((len(connected_positions)))
        group = np.zeros((len(connected_positions)))
        label = np.zeros((len(connected_positions)))
        
        for j in range(len(connected_positions)):
            for i in range(len(connected_positions[j])):
                countxyzlines=0
                for line2 in fileinput.FileInput(name_xyz,inplace=0):
                    countxyzlines = countxyzlines+1
                    if countxyzlines == connected_positions[j][i]+2:
                        if 'C ' in line2:
                            countC[j] = countC[j]+1
                        if 'H ' in line2:
                            countH[j] = countH[j]+1
                        if 'N ' in line2:
                            countN[j] = countN[j]+1
                        if 'O ' in line2:
                            countO[j] = countO[j]+1
                            
        #label between alcohol/carbonyl/ether
            if countC[j] == 1:
                label[j] = 0
            elif countO[j] == 1:
                label[j] = 1
            elif countN[j] == 1:
                label[j] = 2
            else:
                label[j] = 4
                
            
            dt = np.array([[label[j], idx]])
            print(dt)
            datah = np.vstack((datah,dt))
                                 
savetxt('../data/label/5000/label-h.csv',datah,delimiter=',')
os.system('rm ../data/label/5000/*mol')
os.system('rm ../data/label/5000/*xyz')
            

0
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
1
[[2. 1.]]
[[2. 1.]]
[[2. 1.]]
2
[[1. 2.]]
[[1. 2.]]
3
[[0. 3.]]
[[0. 3.]]
4
[[0. 4.]]
5
[[0. 5.]]
[[0. 5.]]
6
[[0. 6.]]
[[0. 6.]]
[[0. 6.]]
[[0. 6.]]
[[0. 6.]]
[[0. 6.]]
7
[[0. 7.]]
[[0. 7.]]
[[0. 7.]]
[[1. 7.]]
8
[[0. 8.]]
[[0. 8.]]
[[0. 8.]]
[[0. 8.]]
9
[[0. 9.]]
[[0. 9.]]
[[0. 9.]]
10
[[ 0. 10.]]
[[ 0. 10.]]
[[ 0. 10.]]
[[ 0. 10.]]
11
[[ 2. 11.]]
[[ 2. 11.]]
[[ 0. 11.]]
12
[[ 0. 12.]]
[[ 0. 12.]]
[[ 0. 12.]]
[[ 0. 12.]]
[[ 0. 12.]]
[[ 0. 12.]]
[[ 0. 12.]]
[[ 0. 12.]]
13
[[ 0. 13.]]
[[ 0. 13.]]
[[ 0. 13.]]
[[ 0. 13.]]
[[ 0. 13.]]
[[ 1. 13.]]
14
[[ 0. 14.]]
[[ 0. 14.]]
[[ 0. 14.]]
[[ 0. 14.]]
[[ 0. 14.]]
[[ 0. 14.]]
15
[[ 0. 15.]]
[[ 0. 15.]]
[[ 0. 15.]]
[[ 0. 15.]]
[[ 0. 15.]]
[[ 0. 15.]]
16
[[ 0. 16.]]
[[ 0. 16.]]
[[ 0. 16.]]
[[ 0. 16.]]
17
[[ 0. 17.]]
[[ 0. 17.]]
[[ 0. 17.]]
[[ 0. 17.]]
[[ 0. 17.]]
[[ 0. 17.]]
18
[[ 0. 18.]]
[[ 0. 18.]]
[[ 0. 18.]]
[[ 2. 18.]]
[[ 2. 18.]]
19
[[ 2. 19.]]
[[ 2. 19.]]
[[ 2. 19.]]
[[ 2. 19.]]
20
[[ 0. 20.]]
[

[[  1. 123.]]
[[  0. 123.]]
[[  0. 123.]]
[[  0. 123.]]
[[  0. 123.]]
124
[[  0. 124.]]
[[  0. 124.]]
[[  0. 124.]]
[[  0. 124.]]
[[  0. 124.]]
[[  0. 124.]]
[[  0. 124.]]
[[  0. 124.]]
125
[[  0. 125.]]
[[  0. 125.]]
[[  0. 125.]]
[[  0. 125.]]
[[  0. 125.]]
[[  2. 125.]]
[[  0. 125.]]
126
[[  0. 126.]]
[[  0. 126.]]
[[  0. 126.]]
[[  0. 126.]]
[[  0. 126.]]
[[  0. 126.]]
127
[[  0. 127.]]
[[  0. 127.]]
[[  0. 127.]]
[[  0. 127.]]
[[  0. 127.]]
[[  0. 127.]]
128
[[  1. 128.]]
[[  0. 128.]]
[[  0. 128.]]
[[  0. 128.]]
[[  0. 128.]]
[[  0. 128.]]
129
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
[[  0. 129.]]
130
[[  0. 130.]]
[[  0. 130.]]
[[  0. 130.]]
[[  0. 130.]]
[[  0. 130.]]
[[  0. 130.]]
[[  0. 130.]]
[[  0. 130.]]
[[  0. 130.]]
[[  1. 130.]]
131
[[  0. 131.]]
[[  0. 131.]]
[[  0. 131.]]
[[  0. 131.]]
[[  0. 131.]]
[[  0. 131.]]
[[  0. 131.]]
[[  0. 131.]]
[[  0. 131.]]
[[

[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  0. 223.]]
[[  1. 223.]]
224
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
[[  0. 224.]]
225
[[  0. 225.]]
[[  0. 225.]]
[[  0. 225.]]
[[  0. 225.]]
[[  0. 225.]]
[[  0. 225.]]
226
[[  0. 226.]]
[[  0. 226.]]
[[  0. 226.]]
[[  2. 226.]]
[[  2. 226.]]
227
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
[[  0. 227.]]
228
[[  0. 228.]]
[[  0. 228.]]
[[  0. 228.]]
[[  0. 228.]]
[[  0. 228.]]
[[  0. 228.]]
[[  0. 228.]]
[[  1. 228.]]
229
[[  0. 229.]]
[[  0. 229.]]
[[  0. 229.]]
[[  0. 229.]]
[[  0. 229.]]
[[  0. 229.]]
230
[[  0. 230.]]
[[  0. 230.]]
[[  0. 230.]]
[[  0. 230.]]
[[  0. 230.]]
231
[[  2. 231.]]
[[  2. 231.]]
[[  0. 231.]]
[[  0. 231.]]
[[  0. 231.]]
23

294
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
[[  0. 294.]]
295
[[  0. 295.]]
[[  0. 295.]]
[[  0. 295.]]
[[  0. 295.]]
[[  0. 295.]]
[[  0. 295.]]
[[  2. 295.]]
296
[[  0. 296.]]
[[  0. 296.]]
[[  0. 296.]]
[[  0. 296.]]
[[  0. 296.]]
[[  0. 296.]]
[[  0. 296.]]
[[  0. 296.]]
297
[[  0. 297.]]
[[  0. 297.]]
[[  0. 297.]]
[[  0. 297.]]
[[  0. 297.]]
[[  0. 297.]]
[[  2. 297.]]
298
[[  0. 298.]]
[[  0. 298.]]
[[  0. 298.]]
[[  0. 298.]]
[[  0. 298.]]
[[  0. 298.]]
299
[[  0. 299.]]
[[  0. 299.]]
[[  0. 299.]]
[[  0. 299.]]
[[  0. 299.]]
[[  0. 299.]]
[[  0. 299.]]
300
[[  1. 300.]]
[[  0. 300.]]
[[  0. 300.]]
[[  0. 300.]]
[[  0. 300.]]
[[  0. 300.]]
301
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
[[  0. 301.]]
302
[[  0. 302.]]
[[  0. 302.]]
[[  0. 302.]]
[[  0. 302.]]
[[  0. 302.]

392
[[  0. 392.]]
[[  0. 392.]]
[[  0. 392.]]
[[  0. 392.]]
[[  0. 392.]]
[[  0. 392.]]
393
[[  0. 393.]]
[[  0. 393.]]
[[  0. 393.]]
[[  0. 393.]]
[[  0. 393.]]
394
[[  2. 394.]]
[[  2. 394.]]
[[  0. 394.]]
[[  0. 394.]]
[[  0. 394.]]
[[  0. 394.]]
395
[[  1. 395.]]
[[  0. 395.]]
[[  0. 395.]]
[[  0. 395.]]
[[  0. 395.]]
[[  0. 395.]]
396
[[  1. 396.]]
[[  0. 396.]]
[[  0. 396.]]
[[  0. 396.]]
[[  0. 396.]]
397
[[  0. 397.]]
[[  0. 397.]]
[[  0. 397.]]
[[  0. 397.]]
[[  0. 397.]]
[[  0. 397.]]
[[  0. 397.]]
[[  0. 397.]]
398
[[  0. 398.]]
[[  0. 398.]]
[[  0. 398.]]
[[  0. 398.]]
[[  0. 398.]]
[[  2. 398.]]
[[  0. 398.]]
399
[[  0. 399.]]
[[  0. 399.]]
[[  0. 399.]]
[[  0. 399.]]
[[  0. 399.]]
[[  0. 399.]]
400
[[  1. 400.]]
[[  0. 400.]]
[[  0. 400.]]
[[  0. 400.]]
[[  0. 400.]]
[[  0. 400.]]
401
[[  0. 401.]]
[[  0. 401.]]
[[  0. 401.]]
[[  0. 401.]]
[[  0. 401.]]
[[  1. 401.]]
[[  0. 401.]]
[[  0. 401.]]
[[  0. 401.]]
[[  0. 401.]]
402
[[  0. 402.]]
[[  0. 402.]]
[[  0. 402.]]
[[  

[[  0. 475.]]
476
477
[[  0. 477.]]
[[  0. 477.]]
[[  0. 477.]]
[[  0. 477.]]
[[  0. 477.]]
[[  0. 477.]]
478
[[  0. 478.]]
[[  0. 478.]]
[[  0. 478.]]
[[  0. 478.]]
[[  0. 478.]]
479
[[  0. 479.]]
[[  0. 479.]]
[[  0. 479.]]
[[  0. 479.]]
480
[[  0. 480.]]
[[  0. 480.]]
481
[[  0. 481.]]
482
[[  0. 482.]]
[[  0. 482.]]
483
[[  2. 483.]]
[[  0. 483.]]
[[  0. 483.]]
[[  0. 483.]]
[[  0. 483.]]
484
[[  2. 484.]]
[[  0. 484.]]
[[  0. 484.]]
[[  0. 484.]]
485
[[  0. 485.]]
[[  0. 485.]]
[[  0. 485.]]
[[  0. 485.]]
[[  0. 485.]]
[[  0. 485.]]
486
[[  0. 486.]]
[[  0. 486.]]
[[  0. 486.]]
[[  0. 486.]]
[[  0. 486.]]
487
[[  0. 487.]]
[[  2. 487.]]
[[  0. 487.]]
[[  0. 487.]]
[[  0. 487.]]
488
[[  0. 488.]]
[[  2. 488.]]
[[  0. 488.]]
[[  0. 488.]]
489
[[  0. 489.]]
[[  0. 489.]]
[[  0. 489.]]
[[  0. 489.]]
490
[[  0. 490.]]
[[  0. 490.]]
[[  0. 490.]]
491
[[  2. 491.]]
[[  0. 491.]]
[[  0. 491.]]
[[  0. 491.]]
[[  0. 491.]]
492
[[  0. 492.]]
[[  0. 492.]]
[[  0. 492.]]
[[  0. 492.]]
[[  0. 4

[[  1. 560.]]
[[  0. 560.]]
[[  0. 560.]]
[[  0. 560.]]
[[  0. 560.]]
[[  0. 560.]]
[[  0. 560.]]
[[  0. 560.]]
561
[[  0. 561.]]
[[  0. 561.]]
[[  0. 561.]]
[[  0. 561.]]
[[  0. 561.]]
[[  0. 561.]]
[[  0. 561.]]
[[  0. 561.]]
562
[[  0. 562.]]
[[  0. 562.]]
[[  0. 562.]]
[[  0. 562.]]
[[  0. 562.]]
[[  0. 562.]]
563
[[  0. 563.]]
[[  0. 563.]]
[[  0. 563.]]
[[  0. 563.]]
[[  0. 563.]]
[[  0. 563.]]
[[  0. 563.]]
564
[[  0. 564.]]
[[  0. 564.]]
[[  0. 564.]]
[[  0. 564.]]
[[  0. 564.]]
[[  0. 564.]]
[[  0. 564.]]
565
[[  0. 565.]]
[[  0. 565.]]
[[  0. 565.]]
[[  0. 565.]]
[[  0. 565.]]
[[  2. 565.]]
566
[[  0. 566.]]
[[  0. 566.]]
[[  0. 566.]]
[[  0. 566.]]
[[  0. 566.]]
567
[[  0. 567.]]
[[  0. 567.]]
[[  0. 567.]]
[[  0. 567.]]
[[  0. 567.]]
[[  0. 567.]]
568
[[  2. 568.]]
[[  0. 568.]]
[[  0. 568.]]
[[  0. 568.]]
[[  0. 568.]]
[[  0. 568.]]
[[  0. 568.]]
569
[[  0. 569.]]
[[  0. 569.]]
[[  0. 569.]]
[[  0. 569.]]
[[  0. 569.]]
[[  0. 569.]]
[[  0. 569.]]
[[  0. 569.]]
570
[[  0. 5

[[  0. 642.]]
[[  0. 642.]]
[[  0. 642.]]
[[  0. 642.]]
[[  0. 642.]]
[[  0. 642.]]
[[  0. 642.]]
[[  0. 642.]]
643
[[  1. 643.]]
[[  0. 643.]]
[[  0. 643.]]
[[  0. 643.]]
[[  0. 643.]]
[[  0. 643.]]
[[  0. 643.]]
[[  0. 643.]]
644
[[  1. 644.]]
[[  0. 644.]]
[[  0. 644.]]
[[  0. 644.]]
[[  0. 644.]]
[[  0. 644.]]
645
[[  0. 645.]]
[[  0. 645.]]
[[  0. 645.]]
[[  0. 645.]]
[[  0. 645.]]
[[  0. 645.]]
[[  0. 645.]]
[[  0. 645.]]
646
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
[[  0. 646.]]
647
[[  0. 647.]]
[[  0. 647.]]
[[  0. 647.]]
[[  0. 647.]]
[[  0. 647.]]
[[  0. 647.]]
[[  0. 647.]]
648
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
[[  0. 648.]]
649
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
[[  0. 649.]]
650
[[

[[  0. 740.]]
[[  0. 740.]]
[[  0. 740.]]
[[  0. 740.]]
741
[[  0. 741.]]
[[  0. 741.]]
[[  0. 741.]]
742
[[  2. 742.]]
[[  2. 742.]]
[[  0. 742.]]
[[  0. 742.]]
[[  2. 742.]]
743
[[  2. 743.]]
[[  2. 743.]]
[[  0. 743.]]
[[  0. 743.]]
744
[[  2. 744.]]
[[  2. 744.]]
[[  0. 744.]]
[[  2. 744.]]
745
[[  2. 745.]]
[[  2. 745.]]
[[  0. 745.]]
746
[[  2. 746.]]
[[  2. 746.]]
[[  0. 746.]]
[[  2. 746.]]
[[  0. 746.]]
747
[[  2. 747.]]
[[  2. 747.]]
[[  0. 747.]]
[[  2. 747.]]
748
[[  2. 748.]]
[[  2. 748.]]
[[  0. 748.]]
[[  0. 748.]]
749
[[  2. 749.]]
[[  2. 749.]]
[[  0. 749.]]
750
[[  2. 750.]]
[[  2. 750.]]
[[  0. 750.]]
[[  2. 750.]]
751
[[  2. 751.]]
[[  2. 751.]]
[[  0. 751.]]
752
[[  2. 752.]]
[[  2. 752.]]
[[  2. 752.]]
[[  0. 752.]]
[[  0. 752.]]
753
[[  2. 753.]]
[[  2. 753.]]
[[  2. 753.]]
[[  0. 753.]]
754
[[  2. 754.]]
[[  2. 754.]]
[[  2. 754.]]
[[  0. 754.]]
755
[[  2. 755.]]
[[  2. 755.]]
[[  2. 755.]]
756
[[  2. 756.]]
[[  2. 756.]]
[[  0. 756.]]
[[  0. 756.]]
757
[[  2. 7

[[  0. 850.]]
[[  0. 850.]]
[[  0. 850.]]
[[  0. 850.]]
[[  0. 850.]]
[[  2. 850.]]
[[  2. 850.]]
851
[[  0. 851.]]
[[  0. 851.]]
[[  0. 851.]]
[[  0. 851.]]
[[  0. 851.]]
[[  1. 851.]]
[[  2. 851.]]
852
[[  0. 852.]]
[[  0. 852.]]
[[  0. 852.]]
[[  0. 852.]]
[[  0. 852.]]
[[  0. 852.]]
[[  0. 852.]]
853
[[  0. 853.]]
[[  0. 853.]]
[[  0. 853.]]
[[  0. 853.]]
[[  2. 853.]]
[[  2. 853.]]
854
[[  0. 854.]]
[[  0. 854.]]
[[  0. 854.]]
[[  0. 854.]]
[[  1. 854.]]
[[  2. 854.]]
855
[[  0. 855.]]
[[  0. 855.]]
[[  0. 855.]]
[[  0. 855.]]
[[  1. 855.]]
856
[[  0. 856.]]
[[  0. 856.]]
[[  0. 856.]]
[[  0. 856.]]
[[  2. 856.]]
[[  2. 856.]]
857
[[  0. 857.]]
[[  0. 857.]]
[[  0. 857.]]
[[  0. 857.]]
[[  1. 857.]]
[[  2. 857.]]
858
[[  2. 858.]]
[[  2. 858.]]
[[  0. 858.]]
[[  0. 858.]]
[[  2. 858.]]
[[  2. 858.]]
[[  2. 858.]]
859
[[  2. 859.]]
[[  2. 859.]]
[[  0. 859.]]
[[  0. 859.]]
[[  2. 859.]]
[[  2. 859.]]
860
[[  2. 860.]]
[[  2. 860.]]
[[  0. 860.]]
[[  0. 860.]]
[[  1. 860.]]
[[  2. 8

[[  0. 959.]]
[[  2. 959.]]
960
[[  0. 960.]]
[[  0. 960.]]
[[  0. 960.]]
[[  0. 960.]]
[[  2. 960.]]
[[  0. 960.]]
[[  0. 960.]]
[[  0. 960.]]
[[  0. 960.]]
961
[[  0. 961.]]
[[  0. 961.]]
[[  0. 961.]]
[[  0. 961.]]
[[  2. 961.]]
[[  0. 961.]]
[[  2. 961.]]
[[  2. 961.]]
962
[[  0. 962.]]
[[  0. 962.]]
[[  0. 962.]]
[[  0. 962.]]
[[  2. 962.]]
[[  0. 962.]]
[[  1. 962.]]
963
[[  0. 963.]]
[[  0. 963.]]
[[  0. 963.]]
[[  0. 963.]]
[[  0. 963.]]
[[  0. 963.]]
[[  0. 963.]]
[[  0. 963.]]
964
[[  0. 964.]]
[[  0. 964.]]
[[  0. 964.]]
[[  0. 964.]]
[[  0. 964.]]
[[  2. 964.]]
[[  2. 964.]]
965
[[  2. 965.]]
[[  2. 965.]]
[[  0. 965.]]
[[  2. 965.]]
[[  0. 965.]]
[[  2. 965.]]
[[  2. 965.]]
966
[[  2. 966.]]
[[  2. 966.]]
[[  0. 966.]]
[[  2. 966.]]
[[  0. 966.]]
[[  1. 966.]]
967
[[  2. 967.]]
[[  2. 967.]]
[[  0. 967.]]
[[  0. 967.]]
[[  2. 967.]]
[[  2. 967.]]
968
[[  1. 968.]]
[[  0. 968.]]
[[  2. 968.]]
[[  0. 968.]]
[[  1. 968.]]
969
[[  0. 969.]]
[[  0. 969.]]
[[  0. 969.]]
[[  0. 9

[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
[[   0. 1057.]]
1058
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
[[   0. 1058.]]
1059
[[   0. 1059.]]
[[   0. 1059.]]
[[   0. 1059.]]
[[   0. 1059.]]
[[   0. 1059.]]
[[   0. 1059.]]
[[1.000e+00 1.059e+03]]
[[   0. 1059.]]
[[   0. 1059.]]
[[   0. 1059.]]
1060
[[   0. 1060.]]
[[   0. 1060.]]
[[   0. 1060.]]
[[   0. 1060.]]
[[   0. 1060.]]
[[   0. 1060.]]
[[1.00e+00 1.06e+03]]
[[   0. 1060.]]
[[   0. 1060.]]
1061
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
[[   0. 1061.]]
1062
[[   0. 1062.]]
[[   0. 1062.]]
[[   0. 1062.]]
[[   0. 1062.]]
[[   0. 1062.]]
[[   0. 1062.]]
[

[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
[[   0. 1113.]]
1114
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[   0. 1114.]]
[[1.000e+00 1.114e+03]]
1115
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
[[   0. 1115.]]
1116
[[   0. 1116.]]
[[   0. 1116.]]
[[   0. 1116.]]
[[1.000e+00 1.116e+03]]
[[   0. 1116.]]
[[   0. 1116.]]
[[   0. 1116.]]
[[   0. 1116.]]
[[   0. 1116.]]
[[1.000e+00 1.116e+03]]
1117
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117.]]
[[   0. 1117

[[   2. 1169.]]
[[   0. 1169.]]
1170
[[   2. 1170.]]
[[   2. 1170.]]
1171
[[   0. 1171.]]
[[   0. 1171.]]
[[   0. 1171.]]
[[   0. 1171.]]
1172
[[   2. 1172.]]
[[   2. 1172.]]
[[   0. 1172.]]
1173
[[   0. 1173.]]
[[   0. 1173.]]
[[   0. 1173.]]
[[   2. 1173.]]
[[   0. 1173.]]
[[   0. 1173.]]
[[   0. 1173.]]
1174
[[   0. 1174.]]
[[   0. 1174.]]
[[   0. 1174.]]
[[   2. 1174.]]
[[   0. 1174.]]
[[   0. 1174.]]
1175
[[   0. 1175.]]
[[   0. 1175.]]
[[   0. 1175.]]
[[   0. 1175.]]
[[   0. 1175.]]
[[   0. 1175.]]
[[   0. 1175.]]
[[   0. 1175.]]
1176
[[   0. 1176.]]
[[   0. 1176.]]
[[   0. 1176.]]
[[   0. 1176.]]
[[   0. 1176.]]
[[   0. 1176.]]
[[   0. 1176.]]
1177
[[   0. 1177.]]
[[   0. 1177.]]
[[   0. 1177.]]
[[   2. 1177.]]
[[   0. 1177.]]
[[   0. 1177.]]
[[   0. 1177.]]
1178
[[   0. 1178.]]
[[   0. 1178.]]
[[   0. 1178.]]
[[   2. 1178.]]
[[   0. 1178.]]
[[   0. 1178.]]
1179
[[   0. 1179.]]
[[   0. 1179.]]
[[   0. 1179.]]
[[   0. 1179.]]
[[   0. 1179.]]
[[   0. 1179.]]
1180
[[   0. 1180.]]
[

[[   0. 1238.]]
[[1.000e+00 1.238e+03]]
1239
[[   0. 1239.]]
[[   0. 1239.]]
[[   0. 1239.]]
[[   0. 1239.]]
[[   0. 1239.]]
[[   0. 1239.]]
[[   0. 1239.]]
[[1.000e+00 1.239e+03]]
1240
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
[[   0. 1240.]]
1241
[[   0. 1241.]]
[[   0. 1241.]]
[[   0. 1241.]]
[[   0. 1241.]]
[[   0. 1241.]]
[[   0. 1241.]]
[[   0. 1241.]]
[[   0. 1241.]]
[[   0. 1241.]]
[[   2. 1241.]]
[[   2. 1241.]]
1242
[[   0. 1242.]]
[[   0. 1242.]]
[[   0. 1242.]]
[[   0. 1242.]]
[[   0. 1242.]]
[[   0. 1242.]]
[[   0. 1242.]]
[[   2. 1242.]]
[[   0. 1242.]]
[[   0. 1242.]]
[[   0. 1242.]]
1243
[[   0. 1243.]]
[[   0. 1243.]]
[[   0. 1243.]]
[[   0. 1243.]]
[[   0. 1243.]]
[[   0. 1243.]]
[[   0. 1243.]]
[[   2. 1243.]]
[[   2. 1243.]]
[[   2. 1243.]]
1244
[[   0. 1244.]]
[[   0. 1244.]]
[[   0. 1244.]]
[[   0. 1244.]]
[[   0. 1244.]]
[[   0. 12

[[   0. 1294.]]
[[   0. 1294.]]
[[   0. 1294.]]
[[1.000e+00 1.294e+03]]
[[   0. 1294.]]
[[   0. 1294.]]
[[   0. 1294.]]
[[   0. 1294.]]
1295
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[   0. 1295.]]
[[1.000e+00 1.295e+03]]
1296
[[   0. 1296.]]
[[   0. 1296.]]
[[   0. 1296.]]
[[   0. 1296.]]
[[   0. 1296.]]
[[   0. 1296.]]
[[   2. 1296.]]
[[   0. 1296.]]
[[   0. 1296.]]
[[   0. 1296.]]
[[1.000e+00 1.296e+03]]
1297
[[   0. 1297.]]
[[   0. 1297.]]
[[   0. 1297.]]
[[   0. 1297.]]
[[   0. 1297.]]
[[   0. 1297.]]
[[   0. 1297.]]
[[   0. 1297.]]
[[   0. 1297.]]
[[1.000e+00 1.297e+03]]
1298
[[   0. 1298.]]
[[   0. 1298.]]
[[   0. 1298.]]
[[1.000e+00 1.298e+03]]
[[   0. 1298.]]
[[   0. 1298.]]
[[   0. 1298.]]
[[   0. 1298.]]
[[   0. 1298.]]
[[1.000e+00 1.298e+03]]
1299
[[   0. 1299.]]
[[   0. 1299.]]
[[   0. 1299.]]
[[   0. 1299.]]
[[   0. 1299.]]
[[   0. 1299.]]
[[   0. 1299.]]

[[1.000e+00 1.365e+03]]
[[   0. 1365.]]
[[   0. 1365.]]
[[   0. 1365.]]
[[   0. 1365.]]
1366
[[1.000e+00 1.366e+03]]
[[   0. 1366.]]
[[   0. 1366.]]
[[   0. 1366.]]
1367
[[   0. 1367.]]
[[   0. 1367.]]
[[   0. 1367.]]
[[   0. 1367.]]
[[   0. 1367.]]
[[   0. 1367.]]
[[   0. 1367.]]
[[   0. 1367.]]
1368
[[   0. 1368.]]
[[   0. 1368.]]
[[   0. 1368.]]
[[   0. 1368.]]
[[   0. 1368.]]
[[   0. 1368.]]
[[   0. 1368.]]
1369
[[   0. 1369.]]
[[   0. 1369.]]
[[   0. 1369.]]
[[   0. 1369.]]
[[   0. 1369.]]
[[   0. 1369.]]
[[   0. 1369.]]
1370
[[   0. 1370.]]
[[   0. 1370.]]
[[   0. 1370.]]
[[   0. 1370.]]
[[   0. 1370.]]
[[   0. 1370.]]
1371
[[1.000e+00 1.371e+03]]
[[   0. 1371.]]
[[   0. 1371.]]
[[   0. 1371.]]
[[   0. 1371.]]
[[   0. 1371.]]
1372
[[1.000e+00 1.372e+03]]
[[   0. 1372.]]
[[   0. 1372.]]
[[   0. 1372.]]
[[   0. 1372.]]
1373
[[   0. 1373.]]
[[   0. 1373.]]
[[   0. 1373.]]
[[   0. 1373.]]
[[   0. 1373.]]
[[   0. 1373.]]
[[   0. 1373.]]
[[   0. 1373.]]
1374
[[   0. 1374.]]
[[   0. 137

[[   0. 1435.]]
[[   0. 1435.]]
[[   0. 1435.]]
[[   0. 1435.]]
[[   0. 1435.]]
[[1.000e+00 1.435e+03]]
[[   0. 1435.]]
[[   0. 1435.]]
1436
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
[[   0. 1436.]]
1437
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
[[   0. 1437.]]
1438
[[   0. 1438.]]
[[   0. 1438.]]
[[   0. 1438.]]
[[   0. 1438.]]
[[   0. 1438.]]
[[   0. 1438.]]
[[   0. 1438.]]
[[   0. 1438.]]
[[   0. 1438.]]
1439
[[1.000e+00 1.439e+03]]
[[   0. 1439.]]
[[   0. 1439.]]
[[   0. 1439.]]
[[1.000e+00 1.439e+03]]
[[   0. 1439.]]
[[   0. 1439.]]
[[   0. 1439.]]
1440
[[1.00e+00 1.44e+03]]
[[   0. 1440.]]
[[   0. 1440.]]
[[   0. 1440.]]
[[1.00e+00 1.44e+03]]
[[   0. 1440.]]
[[   0. 1440.]]
1441
[[   0. 1441.]]
[[   0. 1441.]]
[[   0. 1441.]]
[[   0. 1441.]]
[[   0. 1441.]]
[[   0. 1441.]]
[[1.00

[[   0. 1503.]]
[[   0. 1503.]]
[[   0. 1503.]]
[[   0. 1503.]]
[[   2. 1503.]]
[[   2. 1503.]]
1504
[[   0. 1504.]]
[[   0. 1504.]]
[[   0. 1504.]]
[[   0. 1504.]]
[[   0. 1504.]]
[[   0. 1504.]]
[[   0. 1504.]]
[[   0. 1504.]]
[[1.000e+00 1.504e+03]]
[[   0. 1504.]]
1505
[[   0. 1505.]]
[[   0. 1505.]]
[[   0. 1505.]]
[[   0. 1505.]]
[[   0. 1505.]]
[[   0. 1505.]]
[[   0. 1505.]]
[[   0. 1505.]]
[[1.000e+00 1.505e+03]]
1506
[[   0. 1506.]]
[[   0. 1506.]]
[[   0. 1506.]]
[[   0. 1506.]]
[[   0. 1506.]]
[[   2. 1506.]]
[[   0. 1506.]]
[[   0. 1506.]]
[[   0. 1506.]]
[[   0. 1506.]]
1507
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
[[   0. 1507.]]
1508
[[   0. 1508.]]
[[   0. 1508.]]
[[   0. 1508.]]
[[   0. 1508.]]
[[   0. 1508.]]
[[   0. 1508.]]
[[   0. 1508.]]
[[   0. 1508.]]
[[   0. 1508.]]
1509
[[   0. 1509.]]
[[   0. 1509.]]
[[   0. 1509.]]
[[   2. 1509.]]
[[   0. 1509.]]
[[   0. 15

[[   0. 1561.]]
[[   0. 1561.]]
[[   0. 1561.]]
[[   0. 1561.]]
[[1.000e+00 1.561e+03]]
[[   0. 1561.]]
1562
[[   0. 1562.]]
[[   0. 1562.]]
[[   0. 1562.]]
[[   0. 1562.]]
[[1.000e+00 1.562e+03]]
1563
[[   0. 1563.]]
[[   0. 1563.]]
[[   0. 1563.]]
[[   0. 1563.]]
[[   0. 1563.]]
[[   0. 1563.]]
[[   2. 1563.]]
1564
[[   0. 1564.]]
[[   0. 1564.]]
[[   0. 1564.]]
[[   0. 1564.]]
[[   0. 1564.]]
[[   0. 1564.]]
[[   0. 1564.]]
1565
[[   0. 1565.]]
[[   0. 1565.]]
[[   0. 1565.]]
[[   0. 1565.]]
[[   0. 1565.]]
[[   0. 1565.]]
1566
[[   0. 1566.]]
[[   0. 1566.]]
[[   0. 1566.]]
[[   0. 1566.]]
[[   0. 1566.]]
[[   0. 1566.]]
[[   0. 1566.]]
[[   0. 1566.]]
1567
[[   0. 1567.]]
[[   0. 1567.]]
[[   0. 1567.]]
[[   0. 1567.]]
[[1.000e+00 1.567e+03]]
[[   0. 1567.]]
1568
[[   0. 1568.]]
[[   0. 1568.]]
[[   0. 1568.]]
[[   0. 1568.]]
[[   0. 1568.]]
[[   0. 1568.]]
[[   2. 1568.]]
[[   0. 1568.]]
1569
[[   0. 1569.]]
[[   0. 1569.]]
[[   0. 1569.]]
[[   0. 1569.]]
[[   0. 1569.]]
[[   0. 

[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
[[   0. 1630.]]
1631
[[   0. 1631.]]
[[   0. 1631.]]
[[   0. 1631.]]
[[   0. 1631.]]
[[   0. 1631.]]
[[   0. 1631.]]
[[   0. 1631.]]
[[   0. 1631.]]
[[   2. 1631.]]
[[   2. 1631.]]
1632
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
[[   0. 1632.]]
1633
[[   0. 1633.]]
[[   0. 1633.]]
[[   0. 1633.]]
[[   0. 1633.]]
[[   0. 1633.]]
[[   0. 1633.]]
[[   0. 1633.]]
[[   2. 1633.]]
[[   2. 1633.]]
1634
[[   2. 1634.]]
[[   2. 1634.]]
[[   0. 1634.]]
[[1.000e+00 1.634e+03]]
[[   0. 1634.]]
[[   0. 1634.]]
[[1.000e+00 1.634e+03]]
1635
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[   0. 1635.]]
[[1.000e+00 1.6

[[1.000e+00 1.687e+03]]
[[   0. 1687.]]
[[   0. 1687.]]
[[   0. 1687.]]
[[   0. 1687.]]
[[   0. 1687.]]
[[   0. 1687.]]
[[   0. 1687.]]
1688
[[1.000e+00 1.688e+03]]
[[   0. 1688.]]
[[   0. 1688.]]
[[   0. 1688.]]
[[   0. 1688.]]
[[   0. 1688.]]
[[   0. 1688.]]
1689
[[   0. 1689.]]
[[   0. 1689.]]
[[   0. 1689.]]
[[   0. 1689.]]
[[   0. 1689.]]
[[   0. 1689.]]
[[   0. 1689.]]
[[   2. 1689.]]
[[   0. 1689.]]
1690
[[   0. 1690.]]
[[   0. 1690.]]
[[   0. 1690.]]
[[   0. 1690.]]
[[   0. 1690.]]
[[   0. 1690.]]
[[   0. 1690.]]
[[   0. 1690.]]
1691
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
[[   0. 1691.]]
1692
[[   0. 1692.]]
[[   0. 1692.]]
[[   0. 1692.]]
[[   0. 1692.]]
[[   0. 1692.]]
[[   0. 1692.]]
[[   0. 1692.]]
[[   0. 1692.]]
[[   2. 1692.]]
1693
[[   0. 1693.]]
[[   0. 1693.]]
[[   0. 1693.]]
[[   0. 1693.]]
[[   0. 1693.]]
[[   0. 1693.]]
[[   0. 1693.]]
[[   0. 1693.]]
1694
[[1.0

[[   0. 1744.]]
[[   0. 1744.]]
[[   0. 1744.]]
[[   0. 1744.]]
[[   0. 1744.]]
[[   0. 1744.]]
[[   0. 1744.]]
[[   0. 1744.]]
[[   0. 1744.]]
[[1.000e+00 1.744e+03]]
1745
[[1.000e+00 1.745e+03]]
[[   0. 1745.]]
[[   0. 1745.]]
[[1.000e+00 1.745e+03]]
[[   0. 1745.]]
[[   0. 1745.]]
[[   0. 1745.]]
[[1.000e+00 1.745e+03]]
1746
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
[[   0. 1746.]]
1747
[[   0. 1747.]]
[[   0. 1747.]]
[[   0. 1747.]]
[[   0. 1747.]]
[[   0. 1747.]]
[[   0. 1747.]]
[[   0. 1747.]]
[[   0. 1747.]]
[[   2. 1747.]]
1748
[[   0. 1748.]]
[[   0. 1748.]]
[[   0. 1748.]]
[[   0. 1748.]]
[[   0. 1748.]]
[[   0. 1748.]]
[[   0. 1748.]]
[[   0. 1748.]]
1749
[[   0. 1749.]]
[[   0. 1749.]]
[[   0. 1749.]]
[[1.000e+00 1.749e+03]]
[[   0. 1749.]]
[[   0. 1749.]]
[[   0. 1749.]]
[[   0. 1749.]]
1750
[[   0. 1750.]]
[[   0. 1750.]]
[[   0. 1750.]]
[[   0. 1750.]]
[[   0. 1750.]]
[[

[[   0. 1814.]]
[[   0. 1814.]]
[[   0. 1814.]]
[[   0. 1814.]]
[[   0. 1814.]]
[[   0. 1814.]]
[[   0. 1814.]]
[[   0. 1814.]]
[[   2. 1814.]]
1815
[[   0. 1815.]]
[[   0. 1815.]]
[[   0. 1815.]]
[[   0. 1815.]]
[[   0. 1815.]]
[[   0. 1815.]]
[[   0. 1815.]]
[[   0. 1815.]]
1816
[[   0. 1816.]]
[[   0. 1816.]]
[[   0. 1816.]]
[[   0. 1816.]]
[[   0. 1816.]]
[[   0. 1816.]]
[[   2. 1816.]]
[[   0. 1816.]]
[[   0. 1816.]]
1817
[[   0. 1817.]]
[[   0. 1817.]]
[[   0. 1817.]]
[[   0. 1817.]]
[[   0. 1817.]]
[[   0. 1817.]]
[[   2. 1817.]]
[[   2. 1817.]]
1818
[[   0. 1818.]]
[[   0. 1818.]]
[[   0. 1818.]]
[[   0. 1818.]]
[[   0. 1818.]]
[[   0. 1818.]]
[[   2. 1818.]]
1819
[[   0. 1819.]]
[[   0. 1819.]]
[[   0. 1819.]]
[[   0. 1819.]]
[[   0. 1819.]]
[[   0. 1819.]]
[[   2. 1819.]]
[[   0. 1819.]]
[[   0. 1819.]]
1820
[[   0. 1820.]]
[[   0. 1820.]]
[[   0. 1820.]]
[[   0. 1820.]]
[[   0. 1820.]]
[[   0. 1820.]]
[[   2. 1820.]]
1821
[[   0. 1821.]]
[[   0. 1821.]]
[[   0. 1821.]]
[[   

[[   0. 1871.]]
[[   0. 1871.]]
[[   0. 1871.]]
[[   0. 1871.]]
[[   0. 1871.]]
[[   0. 1871.]]
[[   0. 1871.]]
[[   0. 1871.]]
[[   0. 1871.]]
1872
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
[[   0. 1872.]]
1873
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
[[   0. 1873.]]
1874
[[1.000e+00 1.874e+03]]
[[   0. 1874.]]
[[   0. 1874.]]
[[   0. 1874.]]
[[   0. 1874.]]
[[   0. 1874.]]
[[   0. 1874.]]
[[   0. 1874.]]
[[   0. 1874.]]
[[   0. 1874.]]
1875
[[1.000e+00 1.875e+03]]
[[   0. 1875.]]
[[   0. 1875.]]
[[   0. 1875.]]
[[   0. 1875.]]
[[   0. 1875.]]
[[   0. 1875.]]
[[   0. 1875.]]
1876
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
[[   0. 1876.]]
1877
[[   0. 18

[[   0. 1939.]]
1940
[[   2. 1940.]]
[[   2. 1940.]]
[[   0. 1940.]]
[[   0. 1940.]]
[[   0. 1940.]]
[[   0. 1940.]]
[[   0. 1940.]]
1941
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
[[   0. 1941.]]
1942
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
[[   0. 1942.]]
1943
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
[[   0. 1943.]]
1944
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
[[   0. 1944.]]
1945
[[   0. 1945.]]
[[   0. 19

[[   0. 1996.]]
[[   0. 1996.]]
[[   0. 1996.]]
[[1.000e+00 1.996e+03]]
[[   0. 1996.]]
[[   0. 1996.]]
[[   0. 1996.]]
[[   0. 1996.]]
1997
[[   2. 1997.]]
[[   0. 1997.]]
[[   0. 1997.]]
[[   0. 1997.]]
[[   0. 1997.]]
[[   0. 1997.]]
[[   0. 1997.]]
1998
[[   0. 1998.]]
[[   0. 1998.]]
[[   0. 1998.]]
[[   0. 1998.]]
[[   0. 1998.]]
[[   0. 1998.]]
[[   2. 1998.]]
1999
[[   0. 1999.]]
[[   0. 1999.]]
[[   0. 1999.]]
[[   0. 1999.]]
[[   0. 1999.]]
[[   0. 1999.]]
2000
[[   0. 2000.]]
[[   0. 2000.]]
[[   0. 2000.]]
[[   0. 2000.]]
[[   0. 2000.]]
[[   0. 2000.]]
[[   0. 2000.]]
[[   0. 2000.]]
2001
[[   0. 2001.]]
[[   0. 2001.]]
[[   0. 2001.]]
[[   0. 2001.]]
[[   0. 2001.]]
[[   0. 2001.]]
[[2.000e+00 2.001e+03]]
2002
[[   0. 2002.]]
[[   0. 2002.]]
[[   0. 2002.]]
[[   0. 2002.]]
[[   0. 2002.]]
2003
[[   0. 2003.]]
[[   0. 2003.]]
[[   0. 2003.]]
[[   0. 2003.]]
[[   0. 2003.]]
2004
[[2.000e+00 2.004e+03]]
[[   0. 2004.]]
[[   0. 2004.]]
[[   0. 2004.]]
[[   0. 2004.]]
2005
[[2

[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
[[   0. 2054.]]
2055
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
[[   0. 2055.]]
2056
[[1.000e+00 2.056e+03]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
[[   0. 2056.]]
2057
[[1.000e+00 2.057e+03]]
[[   0. 2057.]]
[[   0. 2057.]]
[[   0. 2057.]]
[[   0. 2057.]]
[[   0. 2057.]]
[[   0. 2057.]]
[[   0. 2057.]]
[[   0. 2057.]]
[[   0. 2057.]]
2058
[[1.000e+00 2.058e+03]]
[[   0. 2058.]]
[[   0. 2058.]]
[[   0. 2058.]]
[[   0. 2058.]]
[[   0. 2058.]]
[[   0. 2058.]]
[[   0. 2058.]]
[[   0. 2058.]]
[[   0. 2058.]]
2059
[[1.000e+00 2.059e+03]]
[[   0. 2059.]]
[[   0. 2059.]]
[[   0. 2059.]]
[[   0. 2059.]]
[[   0. 2059.]]
[[   0. 2059.]]

[[   0. 2124.]]
[[   0. 2124.]]
[[   0. 2124.]]
[[   0. 2124.]]
[[   0. 2124.]]
[[   0. 2124.]]
[[   0. 2124.]]
[[   0. 2124.]]
[[   0. 2124.]]
[[1.000e+00 2.124e+03]]
2125
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
[[   0. 2125.]]
2126
[[1.000e+00 2.126e+03]]
[[   0. 2126.]]
[[   0. 2126.]]
[[   0. 2126.]]
[[   0. 2126.]]
[[   0. 2126.]]
[[   0. 2126.]]
[[   0. 2126.]]
[[   0. 2126.]]
[[1.000e+00 2.126e+03]]
2127
[[1.000e+00 2.127e+03]]
[[   0. 2127.]]
[[   0. 2127.]]
[[   0. 2127.]]
[[   0. 2127.]]
[[   0. 2127.]]
[[   0. 2127.]]
[[1.000e+00 2.127e+03]]
2128
[[   0. 2128.]]
[[   0. 2128.]]
[[   0. 2128.]]
[[   0. 2128.]]
[[   0. 2128.]]
[[1.000e+00 2.128e+03]]
[[   0. 2128.]]
[[   0. 2128.]]
2129
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
[[   0. 2129.]]
2130
[[   0. 2130.]]
[[   0. 21

[[   0. 2178.]]
[[   0. 2178.]]
[[   0. 2178.]]
[[   0. 2178.]]
[[   0. 2178.]]
[[   0. 2178.]]
[[   0. 2178.]]
[[   0. 2178.]]
[[   0. 2178.]]
2179
[[   0. 2179.]]
[[   0. 2179.]]
[[   0. 2179.]]
[[   0. 2179.]]
[[   0. 2179.]]
[[   0. 2179.]]
[[   0. 2179.]]
2180
[[   0. 2180.]]
[[   0. 2180.]]
[[   0. 2180.]]
[[2.00e+00 2.18e+03]]
[[   0. 2180.]]
[[   0. 2180.]]
[[   0. 2180.]]
[[   0. 2180.]]
[[   0. 2180.]]
2181
[[   0. 2181.]]
[[   0. 2181.]]
[[   0. 2181.]]
[[   0. 2181.]]
[[   0. 2181.]]
[[   0. 2181.]]
[[   0. 2181.]]
[[   0. 2181.]]
2182
[[1.000e+00 2.182e+03]]
[[   0. 2182.]]
[[   0. 2182.]]
[[   0. 2182.]]
[[   0. 2182.]]
[[   0. 2182.]]
[[   0. 2182.]]
[[   0. 2182.]]
2183
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
[[   0. 2183.]]
2184
[[   0. 2184.]]
[[   0. 2184.]]
[[   0. 2184.]]
[[   0. 2184.]]
[[   0. 2184.]]
[[   0. 2184.]]
[[   0. 2184

[[1.000e+00 2.245e+03]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
[[   0. 2245.]]
2246
[[1.000e+00 2.246e+03]]
[[   0. 2246.]]
[[   0. 2246.]]
[[   0. 2246.]]
[[   0. 2246.]]
[[   0. 2246.]]
[[   0. 2246.]]
[[   0. 2246.]]
[[   0. 2246.]]
[[   0. 2246.]]
2247
[[1.000e+00 2.247e+03]]
[[   0. 2247.]]
[[   0. 2247.]]
[[   0. 2247.]]
[[   0. 2247.]]
[[   0. 2247.]]
[[   0. 2247.]]
[[   0. 2247.]]
[[   0. 2247.]]
[[   0. 2247.]]
2248
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
[[   0. 2248.]]
2249
[[   0. 2249.]]
[[   0. 2249.]]
[[   0. 2249.]]
[[   0. 2249.]]
[[   0. 2249.]]
[[   0. 2249.]]
[[   0. 2249.]]
[[1.000e+00 2.249e+03]]
2250
[[   0. 2250.]]
[[   0. 2250.]]
[[   0. 2250.]]
[[   0. 2250.]]
[[   0. 2250.]]
[[   0. 2250.]]
[[   0. 2250.]]
[[   0. 2250.]]
[[   0. 2250.]]

[[2.000e+00 2.301e+03]]
[[   0. 2301.]]
[[   0. 2301.]]
[[   0. 2301.]]
[[   0. 2301.]]
[[   0. 2301.]]
[[   0. 2301.]]
2302
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
[[   0. 2302.]]
2303
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
[[   0. 2303.]]
2304
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
[[   0. 2304.]]
2305
[[   0. 2305.]]
[[   0. 2305.]]
[[   0. 2305.]]
[[   0. 2305.]]
[[1.000e+00 2.305e+03]]
[[   0. 2305.]]
[[   0. 2305.]]
[[   0. 2305.]]
[[   0. 2305.]]
[[   0. 2305.]]
[[   0. 2305.]]
[[   0. 2305.]]
2306
[[   0. 2306.]]
[[   0. 2306.]]
[[   0. 2306.]]

[[1.000e+00 2.357e+03]]
[[   0. 2357.]]
[[   0. 2357.]]
[[   0. 2357.]]
[[   0. 2357.]]
[[   0. 2357.]]
[[   0. 2357.]]
[[1.000e+00 2.357e+03]]
2358
[[1.000e+00 2.358e+03]]
[[   0. 2358.]]
[[   0. 2358.]]
[[2.000e+00 2.358e+03]]
[[   0. 2358.]]
[[   0. 2358.]]
[[1.000e+00 2.358e+03]]
2359
[[1.000e+00 2.359e+03]]
[[   0. 2359.]]
[[   0. 2359.]]
[[   0. 2359.]]
[[   0. 2359.]]
[[1.000e+00 2.359e+03]]
2360
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
[[   0. 2360.]]
2361
[[   0. 2361.]]
[[   0. 2361.]]
[[   0. 2361.]]
[[   0. 2361.]]
[[   0. 2361.]]
[[   0. 2361.]]
[[   0. 2361.]]
[[   0. 2361.]]
[[   0. 2361.]]
2362
[[   0. 2362.]]
[[   0. 2362.]]
[[   0. 2362.]]
[[   0. 2362.]]
[[   0. 2362.]]
[[   0. 2362.]]
[[   0. 2362.]]
[[   0. 2362.]]
2363
[[   0. 2363.]]
[[   0. 2363.]]
[[   0. 2363.]]
[[   0. 2363.]]
[[   0. 2363.]]
[[   0. 2363.]]
[[   0. 2363.]]
[[   0. 2363.]]
[[   0. 2363.]]
23

[[1.000e+00 2.427e+03]]
[[   0. 2427.]]
[[   0. 2427.]]
[[   0. 2427.]]
[[   0. 2427.]]
[[   0. 2427.]]
[[   0. 2427.]]
[[   0. 2427.]]
[[   0. 2427.]]
[[   0. 2427.]]
2428
[[1.000e+00 2.428e+03]]
[[   0. 2428.]]
[[   0. 2428.]]
[[   0. 2428.]]
[[   0. 2428.]]
[[   0. 2428.]]
[[   0. 2428.]]
[[   0. 2428.]]
2429
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
[[   0. 2429.]]
2430
[[   0. 2430.]]
[[   0. 2430.]]
[[   0. 2430.]]
[[   0. 2430.]]
[[   0. 2430.]]
[[   0. 2430.]]
[[   0. 2430.]]
[[   0. 2430.]]
[[   0. 2430.]]
2431
[[   0. 2431.]]
[[   0. 2431.]]
[[   0. 2431.]]
[[   0. 2431.]]
[[   0. 2431.]]
[[   0. 2431.]]
[[   0. 2431.]]
[[   0. 2431.]]
2432
[[   0. 2432.]]
[[   0. 2432.]]
[[   0. 2432.]]
[[   0. 2432.]]
[[   0. 2432.]]
[[   0. 2432.]]
[[   0. 2432.]]
[[   0. 2432.]]
[[   0. 2432.]]
2433
[[1.000e+00 2.433e+03]]
[[   0. 2433.]]
[[   0. 2433.]]
[[   0. 2433.]]
[[   0. 2433.]]
[[

[[1.000e+00 2.497e+03]]
[[   0. 2497.]]
[[   0. 2497.]]
[[   0. 2497.]]
[[   0. 2497.]]
[[   0. 2497.]]
[[1.000e+00 2.497e+03]]
[[   0. 2497.]]
[[   0. 2497.]]
[[1.000e+00 2.497e+03]]
2498
[[   0. 2498.]]
[[   0. 2498.]]
[[   0. 2498.]]
[[   0. 2498.]]
[[   0. 2498.]]
[[   0. 2498.]]
2499
[[   0. 2499.]]
[[   0. 2499.]]
[[   0. 2499.]]
[[   0. 2499.]]
[[   0. 2499.]]
2500
[[   0. 2500.]]
[[   0. 2500.]]
[[   0. 2500.]]
[[2.0e+00 2.5e+03]]
[[   0. 2500.]]
2501
[[   0. 2501.]]
[[   0. 2501.]]
[[   0. 2501.]]
[[2.000e+00 2.501e+03]]
2502
[[   0. 2502.]]
[[   0. 2502.]]
[[   0. 2502.]]
[[   0. 2502.]]
2503
[[   0. 2503.]]
[[   0. 2503.]]
[[   0. 2503.]]
2504
[[   0. 2504.]]
[[   0. 2504.]]
[[   0. 2504.]]
[[   0. 2504.]]
2505
[[   0. 2505.]]
[[   0. 2505.]]
[[2.000e+00 2.505e+03]]
2506
[[   0. 2506.]]
[[   0. 2506.]]
2507
[[   0. 2507.]]
[[   0. 2507.]]
[[   0. 2507.]]
[[   0. 2507.]]
[[   0. 2507.]]
[[   0. 2507.]]
2508
[[   0. 2508.]]
[[   0. 2508.]]
[[   0. 2508.]]
[[   0. 2508.]]
[[   

[[   0. 2578.]]
[[   0. 2578.]]
[[   0. 2578.]]
[[   0. 2578.]]
[[   0. 2578.]]
2579
[[2.000e+00 2.579e+03]]
[[   0. 2579.]]
[[   0. 2579.]]
[[   0. 2579.]]
[[   0. 2579.]]
[[   0. 2579.]]
[[   0. 2579.]]
2580
[[   0. 2580.]]
[[   0. 2580.]]
[[   0. 2580.]]
[[   0. 2580.]]
[[   0. 2580.]]
[[   0. 2580.]]
[[   0. 2580.]]
[[   0. 2580.]]
2581
[[   0. 2581.]]
[[   0. 2581.]]
[[   0. 2581.]]
[[   0. 2581.]]
[[   0. 2581.]]
[[2.000e+00 2.581e+03]]
[[   0. 2581.]]
2582
[[   0. 2582.]]
[[   0. 2582.]]
[[   0. 2582.]]
[[   0. 2582.]]
[[   0. 2582.]]
[[   0. 2582.]]
2583
[[   0. 2583.]]
[[   0. 2583.]]
[[   0. 2583.]]
[[2.000e+00 2.583e+03]]
[[   0. 2583.]]
[[   0. 2583.]]
[[   0. 2583.]]
2584
[[   0. 2584.]]
[[   0. 2584.]]
[[   0. 2584.]]
[[   0. 2584.]]
[[   0. 2584.]]
[[   0. 2584.]]
2585
[[   0. 2585.]]
[[   0. 2585.]]
[[   0. 2585.]]
[[   0. 2585.]]
2586
[[   0. 2586.]]
[[   0. 2586.]]
[[   0. 2586.]]
2587
[[   0. 2587.]]
[[   0. 2587.]]
[[   0. 2587.]]
[[   0. 2587.]]
2588
[[   0. 2588.]

[[   0. 2647.]]
[[   0. 2647.]]
[[   0. 2647.]]
[[   0. 2647.]]
[[   0. 2647.]]
[[   0. 2647.]]
[[   0. 2647.]]
2648
[[1.000e+00 2.648e+03]]
[[   0. 2648.]]
[[   0. 2648.]]
[[   0. 2648.]]
[[   0. 2648.]]
[[   0. 2648.]]
[[   0. 2648.]]
2649
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
[[   0. 2649.]]
2650
[[   0. 2650.]]
[[   0. 2650.]]
[[   0. 2650.]]
[[   0. 2650.]]
[[   0. 2650.]]
[[   0. 2650.]]
[[   0. 2650.]]
[[   0. 2650.]]
[[   0. 2650.]]
[[2.00e+00 2.65e+03]]
[[   0. 2650.]]
2651
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
[[   0. 2651.]]
2652
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
[[   0. 2652.]]
2653
[[   0. 2653.]]
[[   0. 2653.]]
[[   0. 2653

[[1.000e+00 2.715e+03]]
[[   0. 2715.]]
[[   0. 2715.]]
[[   0. 2715.]]
[[   0. 2715.]]
[[   0. 2715.]]
2716
[[   0. 2716.]]
[[   0. 2716.]]
[[   0. 2716.]]
[[   0. 2716.]]
[[   0. 2716.]]
[[   0. 2716.]]
[[   0. 2716.]]
[[   0. 2716.]]
[[   0. 2716.]]
2717
[[   0. 2717.]]
[[   0. 2717.]]
[[   0. 2717.]]
[[   0. 2717.]]
[[   0. 2717.]]
[[   0. 2717.]]
[[2.000e+00 2.717e+03]]
[[2.000e+00 2.717e+03]]
2718
[[   0. 2718.]]
[[   0. 2718.]]
[[   0. 2718.]]
[[   0. 2718.]]
[[   0. 2718.]]
[[   0. 2718.]]
[[1.000e+00 2.718e+03]]
2719
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
[[   0. 2719.]]
2720
[[   0. 2720.]]
[[   0. 2720.]]
[[   0. 2720.]]
[[   0. 2720.]]
[[   0. 2720.]]
[[   0. 2720.]]
[[   0. 2720.]]
[[   0. 2720.]]
[[2.00e+00 2.72e+03]]
2721
[[   0. 2721.]]
[[   0. 2721.]]
[[   0. 2721.]]
[[   0. 2721.]]
[[   0. 2721.]]
[[   0. 2721.]]
[[   0. 2721.]]
[[   0. 2721.]]
[[2.000e+00 2.721e+0

[[   0. 2784.]]
[[2.000e+00 2.784e+03]]
[[   0. 2784.]]
[[   0. 2784.]]
2785
[[1.000e+00 2.785e+03]]
[[   0. 2785.]]
[[   0. 2785.]]
[[   0. 2785.]]
[[2.000e+00 2.785e+03]]
[[   0. 2785.]]
2786
[[1.000e+00 2.786e+03]]
[[   0. 2786.]]
[[   0. 2786.]]
[[   0. 2786.]]
[[   0. 2786.]]
[[   0. 2786.]]
2787
[[1.000e+00 2.787e+03]]
[[   0. 2787.]]
[[   0. 2787.]]
[[   0. 2787.]]
[[   0. 2787.]]
2788
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
[[   0. 2788.]]
2789
[[   0. 2789.]]
[[   0. 2789.]]
[[   0. 2789.]]
[[   0. 2789.]]
[[   0. 2789.]]
[[   0. 2789.]]
[[   0. 2789.]]
[[   0. 2789.]]
[[   0. 2789.]]
2790
[[   0. 2790.]]
[[   0. 2790.]]
[[   0. 2790.]]
[[   0. 2790.]]
[[   0. 2790.]]
[[   0. 2790.]]
[[2.00e+00 2.79e+03]]
[[   0. 2790.]]
[[   0. 2790.]]
2791
[[   0. 2791.]]
[[   0. 2791.]]
[[   0. 2791.]]
[[   0. 2791.]]
[[   0. 2791.]]
[[   0. 2791.]]
[[   0. 2791.]]
[[   0. 2791.]]
2792
[[

[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
[[   0. 2854.]]
2855
[[   0. 2855.]]
[[   0. 2855.]]
[[   0. 2855.]]
[[   0. 2855.]]
[[   0. 2855.]]
[[   0. 2855.]]
[[   0. 2855.]]
[[   0. 2855.]]
2856
[[   0. 2856.]]
[[   0. 2856.]]
[[   0. 2856.]]
[[   0. 2856.]]
[[   0. 2856.]]
[[   0. 2856.]]
[[   0. 2856.]]
[[   0. 2856.]]
2857
[[   0. 2857.]]
[[   0. 2857.]]
[[   0. 2857.]]
[[   0. 2857.]]
[[   0. 2857.]]
[[   0. 2857.]]
2858
[[   0. 2858.]]
[[   0. 2858.]]
[[   0. 2858.]]
[[   0. 2858.]]
[[   0. 2858.]]
[[   0. 2858.]]
2859
[[   0. 2859.]]
[[   0. 2859.]]
[[   0. 2859.]]
[[   0. 2859.]]
[[   0. 2859.]]
[[   0. 2859.]]
[[   0. 2859.]]
[[   0. 2859.]]
[[   0. 2859.]]
2860
[[   0. 2860.]]
[[   0. 2860.]]
[[   0. 2860.]]
[[   0. 2860.]]
[[   0. 2860.]]
[[   0. 2860.]]
[[2.00e+00 2.86e+03]]
2861
[[   0. 2861.]]
[[   0. 2861.]]
[[   0. 2861.]]
[[   0. 2861.]]
[[   0. 2861.]]
[[   0. 2861.]]

2922
[[1.000e+00 2.922e+03]]
[[   0. 2922.]]
[[   0. 2922.]]
[[   0. 2922.]]
[[   0. 2922.]]
[[   0. 2922.]]
[[   0. 2922.]]
[[   0. 2922.]]
2923
[[1.000e+00 2.923e+03]]
[[   0. 2923.]]
[[   0. 2923.]]
[[   0. 2923.]]
[[   0. 2923.]]
[[   0. 2923.]]
[[2.000e+00 2.923e+03]]
2924
[[1.000e+00 2.924e+03]]
[[   0. 2924.]]
[[   0. 2924.]]
[[   0. 2924.]]
[[   0. 2924.]]
[[   0. 2924.]]
2925
[[1.000e+00 2.925e+03]]
[[   0. 2925.]]
[[   0. 2925.]]
[[   0. 2925.]]
[[   0. 2925.]]
[[   0. 2925.]]
[[   0. 2925.]]
2926
[[1.000e+00 2.926e+03]]
[[   0. 2926.]]
[[   0. 2926.]]
[[   0. 2926.]]
[[   0. 2926.]]
[[2.000e+00 2.926e+03]]
2927
[[1.000e+00 2.927e+03]]
[[   0. 2927.]]
[[   0. 2927.]]
[[   0. 2927.]]
[[   0. 2927.]]
2928
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
[[   0. 2928.]]
2929
[[   0. 2929.]]
[[   0. 2929.]]
[[   0. 2929.]]
[[   0. 2929.]]
[[   0. 2929.]]
[[   0. 2929.]]
[[   0. 2929.]]


[[   0. 2979.]]
[[   0. 2979.]]
[[   0. 2979.]]
[[   0. 2979.]]
[[   0. 2979.]]
[[   0. 2979.]]
[[   0. 2979.]]
2980
[[   0. 2980.]]
[[   0. 2980.]]
[[   0. 2980.]]
[[   0. 2980.]]
[[   0. 2980.]]
[[   0. 2980.]]
[[   0. 2980.]]
[[   0. 2980.]]
2981
[[   0. 2981.]]
[[   0. 2981.]]
[[2.000e+00 2.981e+03]]
[[   0. 2981.]]
[[   0. 2981.]]
[[   0. 2981.]]
[[   0. 2981.]]
[[   0. 2981.]]
2982
[[   0. 2982.]]
[[   0. 2982.]]
[[   0. 2982.]]
[[   0. 2982.]]
[[   0. 2982.]]
[[   0. 2982.]]
[[   0. 2982.]]
2983
[[   0. 2983.]]
[[   0. 2983.]]
[[   0. 2983.]]
[[   0. 2983.]]
[[   0. 2983.]]
[[   0. 2983.]]
2984
[[   0. 2984.]]
[[   0. 2984.]]
[[   0. 2984.]]
[[   0. 2984.]]
[[2.000e+00 2.984e+03]]
2985
[[   0. 2985.]]
[[   0. 2985.]]
[[   0. 2985.]]
[[   0. 2985.]]
2986
[[2.000e+00 2.986e+03]]
[[   0. 2986.]]
[[   0. 2986.]]
[[   0. 2986.]]
[[   0. 2986.]]
[[   0. 2986.]]
[[   0. 2986.]]
[[2.000e+00 2.986e+03]]
2987
[[2.000e+00 2.987e+03]]
[[   0. 2987.]]
[[   0. 2987.]]
[[   0. 2987.]]
[[   0. 

3036
[[   0. 3036.]]
[[   0. 3036.]]
[[   0. 3036.]]
[[   0. 3036.]]
[[   0. 3036.]]
[[   0. 3036.]]
[[   0. 3036.]]
[[   0. 3036.]]
[[   0. 3036.]]
3037
[[   0. 3037.]]
[[   0. 3037.]]
[[   0. 3037.]]
[[   0. 3037.]]
[[   0. 3037.]]
[[1.000e+00 3.037e+03]]
[[   0. 3037.]]
[[   0. 3037.]]
3038
[[1.000e+00 3.038e+03]]
[[   0. 3038.]]
[[   0. 3038.]]
[[1.000e+00 3.038e+03]]
[[   0. 3038.]]
[[   0. 3038.]]
3039
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[   0. 3039.]]
[[1.000e+00 3.039e+03]]
3040
[[   0. 3040.]]
[[   0. 3040.]]
[[   0. 3040.]]
[[   0. 3040.]]
[[   0. 3040.]]
[[   0. 3040.]]
[[   0. 3040.]]
[[1.00e+00 3.04e+03]]
[[   0. 3040.]]
[[   0. 3040.]]
[[   0. 3040.]]
3041
[[   0. 3041.]]
[[   0. 3041.]]
[[   0. 3041.]]
[[   0. 3041.]]
[[   0. 3041.]]
[[1.000e+00 3.041e+03]]
[[   0. 3041.]]
[[   0. 3041.]]
[[   0. 3041.]]
[[1.000e+00 3.041e+03]]
3042
[[   0. 3042.]]

[[   0. 3103.]]
[[   0. 3103.]]
[[   0. 3103.]]
[[   0. 3103.]]
[[   0. 3103.]]
[[   0. 3103.]]
[[   0. 3103.]]
[[   0. 3103.]]
3104
[[1.000e+00 3.104e+03]]
[[   0. 3104.]]
[[   0. 3104.]]
[[   0. 3104.]]
[[   0. 3104.]]
[[   0. 3104.]]
[[   0. 3104.]]
[[   0. 3104.]]
[[   0. 3104.]]
[[   0. 3104.]]
3105
[[1.000e+00 3.105e+03]]
[[   0. 3105.]]
[[   0. 3105.]]
[[   0. 3105.]]
[[   0. 3105.]]
[[   0. 3105.]]
[[   0. 3105.]]
[[   0. 3105.]]
[[2.000e+00 3.105e+03]]
3106
[[1.000e+00 3.106e+03]]
[[   0. 3106.]]
[[   0. 3106.]]
[[   0. 3106.]]
[[   0. 3106.]]
[[   0. 3106.]]
[[   0. 3106.]]
[[   0. 3106.]]
3107
[[1.000e+00 3.107e+03]]
[[   0. 3107.]]
[[   0. 3107.]]
[[   0. 3107.]]
[[   0. 3107.]]
[[   0. 3107.]]
[[   0. 3107.]]
[[   0. 3107.]]
3108
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
[[   0. 3108.]]
3109
[[   0. 3109.]]
[[   0. 3109.]]
[[   0. 3109.]]
[[   0. 3109.]]
[[   0. 3109.]]
[[

[[   0. 3170.]]
[[   0. 3170.]]
[[   0. 3170.]]
[[   0. 3170.]]
[[   0. 3170.]]
[[   0. 3170.]]
[[   0. 3170.]]
[[   0. 3170.]]
3171
[[   0. 3171.]]
[[   0. 3171.]]
[[   0. 3171.]]
[[   0. 3171.]]
[[   0. 3171.]]
[[   0. 3171.]]
[[   0. 3171.]]
[[   0. 3171.]]
[[   0. 3171.]]
3172
[[   0. 3172.]]
[[   0. 3172.]]
[[   0. 3172.]]
[[2.000e+00 3.172e+03]]
[[   0. 3172.]]
[[   0. 3172.]]
[[   0. 3172.]]
[[   0. 3172.]]
[[   0. 3172.]]
3173
[[   0. 3173.]]
[[   0. 3173.]]
[[   0. 3173.]]
[[2.000e+00 3.173e+03]]
[[   0. 3173.]]
[[   0. 3173.]]
[[2.000e+00 3.173e+03]]
[[   0. 3173.]]
3174
[[   0. 3174.]]
[[   0. 3174.]]
[[   0. 3174.]]
[[2.000e+00 3.174e+03]]
[[   0. 3174.]]
[[   0. 3174.]]
[[   0. 3174.]]
3175
[[   0. 3175.]]
[[   0. 3175.]]
[[   0. 3175.]]
[[   0. 3175.]]
[[   0. 3175.]]
[[   0. 3175.]]
[[   0. 3175.]]
[[   0. 3175.]]
3176
[[   0. 3176.]]
[[   0. 3176.]]
[[   0. 3176.]]
[[   0. 3176.]]
[[   0. 3176.]]
[[2.000e+00 3.176e+03]]
[[   0. 3176.]]
3177
[[   0. 3177.]]
[[   0. 3177.

[[   0. 3239.]]
[[   0. 3239.]]
[[   0. 3239.]]
[[   0. 3239.]]
[[   0. 3239.]]
[[   0. 3239.]]
3240
[[   0. 3240.]]
[[   0. 3240.]]
[[   0. 3240.]]
[[   0. 3240.]]
[[   0. 3240.]]
[[   0. 3240.]]
[[   0. 3240.]]
[[   0. 3240.]]
3241
[[   0. 3241.]]
[[   0. 3241.]]
[[   0. 3241.]]
[[   0. 3241.]]
[[   0. 3241.]]
[[   0. 3241.]]
[[   0. 3241.]]
3242
[[   0. 3242.]]
[[   0. 3242.]]
[[   0. 3242.]]
[[   0. 3242.]]
[[   0. 3242.]]
[[2.000e+00 3.242e+03]]
[[   0. 3242.]]
3243
[[   0. 3243.]]
[[   0. 3243.]]
[[   0. 3243.]]
[[   0. 3243.]]
[[   0. 3243.]]
[[   0. 3243.]]
3244
[[   0. 3244.]]
[[   0. 3244.]]
[[   0. 3244.]]
[[   0. 3244.]]
[[   0. 3244.]]
[[   0. 3244.]]
3245
[[   0. 3245.]]
[[   0. 3245.]]
[[   0. 3245.]]
[[   0. 3245.]]
[[   0. 3245.]]
[[   0. 3245.]]
[[   0. 3245.]]
3246
[[   0. 3246.]]
[[   0. 3246.]]
[[   0. 3246.]]
[[   0. 3246.]]
[[   0. 3246.]]
[[   0. 3246.]]
3247
[[   0. 3247.]]
[[   0. 3247.]]
[[   0. 3247.]]
[[   0. 3247.]]
[[2.000e+00 3.247e+03]]
[[   0. 3247.]]


[[1.000e+00 3.307e+03]]
[[   0. 3307.]]
[[   0. 3307.]]
[[   0. 3307.]]
[[   0. 3307.]]
[[   0. 3307.]]
[[   0. 3307.]]
[[   0. 3307.]]
3308
[[1.000e+00 3.308e+03]]
[[   0. 3308.]]
[[   0. 3308.]]
[[   0. 3308.]]
[[   0. 3308.]]
3309
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
[[   0. 3309.]]
3310
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
[[   0. 3310.]]
3311
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
[[   0. 3311.]]
3312
[[   0. 3312.]]
[[   0. 3312.]]
[[   0. 3312.]]
[[   0. 3312.]]
[[   0. 3312.]]
[[   0. 3312.]]
[[   0. 3312.]]
[[   0. 3312.]]
3313
[[   0. 3313.]]
[[   0. 3313.]]
[[   0. 3313.]]
[[   0. 3313.]]
[[   0. 3313.]]
[[   0. 3313.]]
[[   0. 33

[[   0. 3375.]]
[[   0. 3375.]]
[[   0. 3375.]]
[[   0. 3375.]]
3376
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
[[   0. 3376.]]
3377
[[   0. 3377.]]
[[   0. 3377.]]
[[   0. 3377.]]
[[   0. 3377.]]
[[   0. 3377.]]
[[   0. 3377.]]
[[   0. 3377.]]
[[2.000e+00 3.377e+03]]
[[   0. 3377.]]
3378
[[   0. 3378.]]
[[   0. 3378.]]
[[   0. 3378.]]
[[   0. 3378.]]
[[   0. 3378.]]
[[   0. 3378.]]
[[   0. 3378.]]
[[   0. 3378.]]
3379
[[2.000e+00 3.379e+03]]
[[2.000e+00 3.379e+03]]
[[   0. 3379.]]
[[   0. 3379.]]
[[   0. 3379.]]
[[   0. 3379.]]
3380
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
[[   0. 3380.]]
3381
[[   0. 3381.]]
[[   0. 3381.]]
[[   0. 3381.]]
[[   0. 3381.]]
[[   0. 3381.]]
[[   0. 3381.]]
[[   0. 3381.]]
[[2.000e+00 3.381e+03]]
[[   0. 3381.]]
3382
[[   0. 3382.]]
[[   0. 3382.]]
[[   

[[   0. 3444.]]
[[   0. 3444.]]
[[   0. 3444.]]
[[   0. 3444.]]
[[   0. 3444.]]
[[   0. 3444.]]
[[   0. 3444.]]
[[   0. 3444.]]
3445
[[   0. 3445.]]
[[   0. 3445.]]
[[   0. 3445.]]
[[   0. 3445.]]
[[   0. 3445.]]
[[   0. 3445.]]
3446
[[   0. 3446.]]
[[   0. 3446.]]
[[   0. 3446.]]
[[   0. 3446.]]
[[   0. 3446.]]
[[   0. 3446.]]
[[   0. 3446.]]
3447
[[   0. 3447.]]
[[   0. 3447.]]
[[   0. 3447.]]
[[   0. 3447.]]
[[   0. 3447.]]
[[   0. 3447.]]
[[   0. 3447.]]
3448
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
[[   0. 3448.]]
3449
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
[[   0. 3449.]]
3450
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
[[   0. 3450.]]
3451
[[   

3512
[[   0. 3512.]]
[[   0. 3512.]]
[[   0. 3512.]]
[[   0. 3512.]]
[[   0. 3512.]]
[[   0. 3512.]]
[[   0. 3512.]]
[[   0. 3512.]]
3513
[[   0. 3513.]]
[[   0. 3513.]]
[[   0. 3513.]]
[[   0. 3513.]]
[[2.000e+00 3.513e+03]]
[[   0. 3513.]]
[[   0. 3513.]]
3514
[[   0. 3514.]]
[[   0. 3514.]]
[[   0. 3514.]]
[[   0. 3514.]]
[[   0. 3514.]]
[[   0. 3514.]]
3515
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
[[   0. 3515.]]
3516
[[   0. 3516.]]
[[   0. 3516.]]
[[   0. 3516.]]
[[   0. 3516.]]
[[   0. 3516.]]
[[   0. 3516.]]
[[   0. 3516.]]
[[   0. 3516.]]
[[   0. 3516.]]
3517
[[   0. 3517.]]
[[   0. 3517.]]
[[   0. 3517.]]
[[   0. 3517.]]
[[   0. 3517.]]
[[   0. 3517.]]
[[   0. 3517.]]
[[   0. 3517.]]
[[   0. 3517.]]
3518
[[   0. 3518.]]
[[   0. 3518.]]
[[   0. 3518.]]
[[   0. 3518.]]
[[   0. 3518.]]
[[   0. 3518.]]
[[2.000e+00 3.518e+03]]
[[   0. 3518.]]
[[   0. 3518.]]
3519
[[   0. 3519.]]


[[   0. 3580.]]
[[   0. 3580.]]
[[2.00e+00 3.58e+03]]
3581
[[   0. 3581.]]
[[   0. 3581.]]
[[   0. 3581.]]
3582
[[   0. 3582.]]
[[   0. 3582.]]
3583
[[   0. 3583.]]
[[   0. 3583.]]
3584
[[   0. 3584.]]
[[2.000e+00 3.584e+03]]
[[   0. 3584.]]
[[   0. 3584.]]
3585
[[   0. 3585.]]
[[2.000e+00 3.585e+03]]
[[   0. 3585.]]
3586
[[   0. 3586.]]
[[2.000e+00 3.586e+03]]
[[   0. 3586.]]
3587
[[   0. 3587.]]
[[2.000e+00 3.587e+03]]
3588
[[   0. 3588.]]
[[   0. 3588.]]
[[   0. 3588.]]
3589
[[   0. 3589.]]
[[   0. 3589.]]
3590
[[   0. 3590.]]
[[   0. 3590.]]
3591
[[   0. 3591.]]
3592
[[   0. 3592.]]
[[   0. 3592.]]
[[   0. 3592.]]
[[   0. 3592.]]
[[   0. 3592.]]
[[   0. 3592.]]
3593
[[   0. 3593.]]
[[   0. 3593.]]
[[   0. 3593.]]
[[   0. 3593.]]
[[   0. 3593.]]
3594
[[   0. 3594.]]
[[   0. 3594.]]
[[   0. 3594.]]
[[   0. 3594.]]
[[   0. 3594.]]
3595
[[   0. 3595.]]
[[   0. 3595.]]
[[   0. 3595.]]
[[   0. 3595.]]
[[   0. 3595.]]
[[   0. 3595.]]
[[   0. 3595.]]
[[2.000e+00 3.595e+03]]
3596
[[   0. 35

[[   0. 3665.]]
[[   0. 3665.]]
[[   0. 3665.]]
[[   0. 3665.]]
[[   0. 3665.]]
[[2.000e+00 3.665e+03]]
[[   0. 3665.]]
3666
[[   0. 3666.]]
[[   0. 3666.]]
[[   0. 3666.]]
[[   0. 3666.]]
[[   0. 3666.]]
[[2.000e+00 3.666e+03]]
[[   0. 3666.]]
3667
[[   0. 3667.]]
[[   0. 3667.]]
[[   0. 3667.]]
[[   0. 3667.]]
[[   0. 3667.]]
[[2.000e+00 3.667e+03]]
3668
[[   0. 3668.]]
[[   0. 3668.]]
[[   0. 3668.]]
[[   0. 3668.]]
[[   0. 3668.]]
[[   0. 3668.]]
[[   0. 3668.]]
3669
[[   0. 3669.]]
[[   0. 3669.]]
[[   0. 3669.]]
[[   0. 3669.]]
[[   0. 3669.]]
[[   0. 3669.]]
3670
[[   0. 3670.]]
[[   0. 3670.]]
[[   0. 3670.]]
[[   0. 3670.]]
[[   0. 3670.]]
[[   0. 3670.]]
3671
[[   0. 3671.]]
[[   0. 3671.]]
[[   0. 3671.]]
[[   0. 3671.]]
[[   0. 3671.]]
3672
[[   0. 3672.]]
[[   0. 3672.]]
[[   0. 3672.]]
[[   0. 3672.]]
[[   0. 3672.]]
[[   0. 3672.]]
[[   0. 3672.]]
[[   0. 3672.]]
3673
[[   0. 3673.]]
[[   0. 3673.]]
[[   0. 3673.]]
[[   0. 3673.]]
[[   0. 3673.]]
[[   0. 3673.]]
[[   0. 

[[   0. 3749.]]
[[   0. 3749.]]
[[   0. 3749.]]
[[   0. 3749.]]
3750
[[   0. 3750.]]
[[   0. 3750.]]
[[   0. 3750.]]
3751
[[   0. 3751.]]
[[   0. 3751.]]
[[2.000e+00 3.751e+03]]
3752
[[   0. 3752.]]
[[   0. 3752.]]
3753
[[   0. 3753.]]
3754
[[   0. 3754.]]
[[2.000e+00 3.754e+03]]
[[   0. 3754.]]
3755
[[   0. 3755.]]
[[2.000e+00 3.755e+03]]
3756
[[   0. 3756.]]
[[   0. 3756.]]
3757
[[   0. 3757.]]
3758
[[   0. 3758.]]
3759
[[2.000e+00 3.759e+03]]
[[   0. 3759.]]
[[   0. 3759.]]
3760
[[2.00e+00 3.76e+03]]
[[   0. 3760.]]
3761
[[2.000e+00 3.761e+03]]
[[   0. 3761.]]
3762
[[   0. 3762.]]
[[   0. 3762.]]
3763
[[   0. 3763.]]
3764
[[   0. 3764.]]
3765
3766
[[2.000e+00 3.766e+03]]
[[   0. 3766.]]
[[   0. 3766.]]
[[2.000e+00 3.766e+03]]
3767
[[2.000e+00 3.767e+03]]
[[   0. 3767.]]
[[   0. 3767.]]
[[   0. 3767.]]
3768
[[2.000e+00 3.768e+03]]
[[   0. 3768.]]
[[   0. 3768.]]
3769
[[2.000e+00 3.769e+03]]
[[   0. 3769.]]
[[2.000e+00 3.769e+03]]
[[   0. 3769.]]
3770
[[2.00e+00 3.77e+03]]
[[   0. 377

[[1.000e+00 3.873e+03]]
[[2.000e+00 3.873e+03]]
[[1.000e+00 3.873e+03]]
3874
[[1.000e+00 3.874e+03]]
3875
[[1.000e+00 3.875e+03]]
[[   0. 3875.]]
[[   0. 3875.]]
[[   0. 3875.]]
[[   0. 3875.]]
[[2.000e+00 3.875e+03]]
3876
[[1.000e+00 3.876e+03]]
[[   0. 3876.]]
[[   0. 3876.]]
[[   0. 3876.]]
[[   0. 3876.]]
3877
[[1.000e+00 3.877e+03]]
[[   0. 3877.]]
[[   0. 3877.]]
[[   0. 3877.]]
[[2.000e+00 3.877e+03]]
3878
[[1.000e+00 3.878e+03]]
[[   0. 3878.]]
[[   0. 3878.]]
[[   0. 3878.]]
3879
[[1.000e+00 3.879e+03]]
[[   0. 3879.]]
[[   0. 3879.]]
[[   0. 3879.]]
[[2.000e+00 3.879e+03]]
[[   0. 3879.]]
3880
[[1.00e+00 3.88e+03]]
[[   0. 3880.]]
[[   0. 3880.]]
[[   0. 3880.]]
[[2.00e+00 3.88e+03]]
3881
[[1.000e+00 3.881e+03]]
[[   0. 3881.]]
[[   0. 3881.]]
[[   0. 3881.]]
[[   0. 3881.]]
3882
[[1.000e+00 3.882e+03]]
[[   0. 3882.]]
[[   0. 3882.]]
[[   0. 3882.]]
3883
[[1.000e+00 3.883e+03]]
[[   0. 3883.]]
[[   0. 3883.]]
[[   0. 3883.]]
[[2.000e+00 3.883e+03]]
3884
[[1.000e+00 3.884e+03

[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[   0. 3940.]]
[[1.00e+00 3.94e+03]]
3941
[[   0. 3941.]]
[[   0. 3941.]]
[[   0. 3941.]]
[[   0. 3941.]]
[[   0. 3941.]]
[[   0. 3941.]]
[[   0. 3941.]]
[[   0. 3941.]]
[[   0. 3941.]]
[[1.000e+00 3.941e+03]]
[[1.000e+00 3.941e+03]]
3942
[[2.000e+00 3.942e+03]]
[[2.000e+00 3.942e+03]]
[[   0. 3942.]]
[[   0. 3942.]]
[[   0. 3942.]]
[[   0. 3942.]]
[[   0. 3942.]]
[[   0. 3942.]]
[[   0. 3942.]]
[[1.000e+00 3.942e+03]]
3943
[[1.000e+00 3.943e+03]]
[[   0. 3943.]]
[[   0. 3943.]]
[[   0. 3943.]]
[[   0. 3943.]]
[[   0. 3943.]]
[[   0. 3943.]]
[[1.000e+00 3.943e+03]]
[[1.000e+00 3.943e+03]]
3944
[[   0. 3944.]]
[[   0. 3944.]]
[[   0. 3944.]]
[[1.000e+00 3.944e+03]]
[[1.000e+00 3.944e+03]]
[[   0. 3944.]]
3945
[[2.000e+00 3.945e+03]]
[[2.000e+00 3.945e+03]]
[[2.000e+00 3.945e+03]]
[[2.000e+00 3.945e+03]]
3946
[[2.

[[   0. 3995.]]
[[   0. 3995.]]
[[   0. 3995.]]
[[   0. 3995.]]
[[   0. 3995.]]
[[   0. 3995.]]
[[   0. 3995.]]
[[   0. 3995.]]
[[1.000e+00 3.995e+03]]
3996
[[1.000e+00 3.996e+03]]
[[   0. 3996.]]
[[   0. 3996.]]
[[   0. 3996.]]
[[   0. 3996.]]
[[   0. 3996.]]
[[   0. 3996.]]
[[   0. 3996.]]
[[1.000e+00 3.996e+03]]
3997
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[   0. 3997.]]
[[1.000e+00 3.997e+03]]
3998
[[   0. 3998.]]
[[   0. 3998.]]
[[   0. 3998.]]
[[   0. 3998.]]
[[   0. 3998.]]
[[   0. 3998.]]
[[   0. 3998.]]
[[   0. 3998.]]
[[1.000e+00 3.998e+03]]
3999
[[   0. 3999.]]
[[   0. 3999.]]
[[   0. 3999.]]
[[   0. 3999.]]
[[   0. 3999.]]
[[   0. 3999.]]
[[   0. 3999.]]
[[   0. 3999.]]
[[   0. 3999.]]
[[1.000e+00 3.999e+03]]
4000
[[1.e+00 4.e+03]]
[[   0. 4000.]]
[[   0. 4000.]]
[[   0. 4000.]]
[[   0. 4000.]]
[[   0. 4000.]]
[[   0. 4000.]]
[[   0. 4000.]]
[[   0. 4000.]]
4001
[[1.000e

[[   0. 4062.]]
[[   0. 4062.]]
[[   0. 4062.]]
[[   0. 4062.]]
[[   0. 4062.]]
[[   0. 4062.]]
[[   0. 4062.]]
[[   0. 4062.]]
[[1.000e+00 4.062e+03]]
4063
[[   0. 4063.]]
[[   0. 4063.]]
[[   0. 4063.]]
[[   0. 4063.]]
[[   0. 4063.]]
[[2.000e+00 4.063e+03]]
[[   0. 4063.]]
[[1.000e+00 4.063e+03]]
4064
[[   0. 4064.]]
[[   0. 4064.]]
[[   0. 4064.]]
[[   0. 4064.]]
[[   0. 4064.]]
[[   0. 4064.]]
[[1.000e+00 4.064e+03]]
4065
[[   0. 4065.]]
[[   0. 4065.]]
[[   0. 4065.]]
[[   0. 4065.]]
[[   0. 4065.]]
[[   0. 4065.]]
[[   0. 4065.]]
[[1.000e+00 4.065e+03]]
4066
[[1.000e+00 4.066e+03]]
[[   0. 4066.]]
[[   0. 4066.]]
[[   0. 4066.]]
[[   0. 4066.]]
[[   0. 4066.]]
[[1.000e+00 4.066e+03]]
4067
[[1.000e+00 4.067e+03]]
[[   0. 4067.]]
[[2.000e+00 4.067e+03]]
[[   0. 4067.]]
[[   0. 4067.]]
[[1.000e+00 4.067e+03]]
4068
[[1.000e+00 4.068e+03]]
[[   0. 4068.]]
[[   0. 4068.]]
[[   0. 4068.]]
[[1.000e+00 4.068e+03]]
4069
[[1.000e+00 4.069e+03]]
[[   0. 4069.]]
[[   0. 4069.]]
[[   0. 4069.

[[1.000e+00 4.129e+03]]
[[   0. 4129.]]
[[   0. 4129.]]
[[   0. 4129.]]
[[   0. 4129.]]
[[   0. 4129.]]
[[   0. 4129.]]
[[2.000e+00 4.129e+03]]
4130
[[1.00e+00 4.13e+03]]
[[   0. 4130.]]
[[   0. 4130.]]
[[   0. 4130.]]
[[   0. 4130.]]
[[   0. 4130.]]
[[   0. 4130.]]
4131
[[1.000e+00 4.131e+03]]
[[   0. 4131.]]
[[   0. 4131.]]
[[   0. 4131.]]
[[   0. 4131.]]
[[   0. 4131.]]
4132
[[1.000e+00 4.132e+03]]
[[   0. 4132.]]
[[   0. 4132.]]
[[   0. 4132.]]
[[   0. 4132.]]
[[   0. 4132.]]
[[   0. 4132.]]
4133
[[1.000e+00 4.133e+03]]
[[   0. 4133.]]
[[   0. 4133.]]
[[   0. 4133.]]
[[   0. 4133.]]
[[   0. 4133.]]
4134
[[1.000e+00 4.134e+03]]
[[   0. 4134.]]
[[   0. 4134.]]
[[   0. 4134.]]
[[   0. 4134.]]
4135
[[   0. 4135.]]
[[   0. 4135.]]
[[   0. 4135.]]
[[   0. 4135.]]
[[   0. 4135.]]
4136
[[   0. 4136.]]
[[   0. 4136.]]
[[   0. 4136.]]
[[   0. 4136.]]
4137
[[   0. 4137.]]
[[   0. 4137.]]
[[   0. 4137.]]
[[   0. 4137.]]
4138
[[   0. 4138.]]
[[   0. 4138.]]
[[   0. 4138.]]
4139
[[   0. 4139.]]


[[1.000e+00 4.238e+03]]
[[   0. 4238.]]
[[2.000e+00 4.238e+03]]
[[   0. 4238.]]
[[   0. 4238.]]
4239
[[1.000e+00 4.239e+03]]
[[   0. 4239.]]
[[2.000e+00 4.239e+03]]
[[   0. 4239.]]
4240
[[1.00e+00 4.24e+03]]
[[   0. 4240.]]
[[2.00e+00 4.24e+03]]
[[   0. 4240.]]
[[   0. 4240.]]
4241
[[1.000e+00 4.241e+03]]
[[   0. 4241.]]
[[2.000e+00 4.241e+03]]
[[   0. 4241.]]
4242
[[1.000e+00 4.242e+03]]
[[   0. 4242.]]
[[   0. 4242.]]
4243
[[1.000e+00 4.243e+03]]
[[2.000e+00 4.243e+03]]
[[   0. 4243.]]
[[   0. 4243.]]
4244
[[1.000e+00 4.244e+03]]
[[2.000e+00 4.244e+03]]
[[   0. 4244.]]
4245
[[1.000e+00 4.245e+03]]
[[2.000e+00 4.245e+03]]
[[   0. 4245.]]
[[   0. 4245.]]
4246
[[1.000e+00 4.246e+03]]
[[2.000e+00 4.246e+03]]
[[   0. 4246.]]
4247
[[1.000e+00 4.247e+03]]
[[   0. 4247.]]
[[   0. 4247.]]
4248
[[1.000e+00 4.248e+03]]
[[   0. 4248.]]
4249
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.]]
[[   0. 4249.

[[2.00e+00 4.32e+03]]
[[2.00e+00 4.32e+03]]
[[   0. 4320.]]
[[   0. 4320.]]
4321
[[2.000e+00 4.321e+03]]
[[2.000e+00 4.321e+03]]
[[   0. 4321.]]
[[2.000e+00 4.321e+03]]
4322
[[2.000e+00 4.322e+03]]
[[2.000e+00 4.322e+03]]
[[   0. 4322.]]
[[2.000e+00 4.322e+03]]
4323
[[2.000e+00 4.323e+03]]
[[2.000e+00 4.323e+03]]
[[   0. 4323.]]
4324
[[1.000e+00 4.324e+03]]
[[   0. 4324.]]
[[   0. 4324.]]
[[   0. 4324.]]
[[2.000e+00 4.324e+03]]
4325
[[1.000e+00 4.325e+03]]
[[   0. 4325.]]
[[   0. 4325.]]
[[   0. 4325.]]
[[2.000e+00 4.325e+03]]
4326
[[1.000e+00 4.326e+03]]
[[   0. 4326.]]
[[   0. 4326.]]
[[   0. 4326.]]
4327
[[1.000e+00 4.327e+03]]
[[   0. 4327.]]
[[   0. 4327.]]
[[2.000e+00 4.327e+03]]
4328
[[1.000e+00 4.328e+03]]
[[   0. 4328.]]
[[   0. 4328.]]
4329
[[1.000e+00 4.329e+03]]
[[   0. 4329.]]
[[   0. 4329.]]
[[2.000e+00 4.329e+03]]
[[2.000e+00 4.329e+03]]
4330
[[1.00e+00 4.33e+03]]
[[   0. 4330.]]
[[   0. 4330.]]
[[2.00e+00 4.33e+03]]
4331
[[1.000e+00 4.331e+03]]
[[   0. 4331.]]
[[   0. 4

[[   0. 4389.]]
[[   0. 4389.]]
[[   0. 4389.]]
[[   0. 4389.]]
[[2.000e+00 4.389e+03]]
[[2.000e+00 4.389e+03]]
[[1.000e+00 4.389e+03]]
[[2.000e+00 4.389e+03]]
4390
[[   0. 4390.]]
[[   0. 4390.]]
[[   0. 4390.]]
[[   0. 4390.]]
[[2.00e+00 4.39e+03]]
[[2.00e+00 4.39e+03]]
[[1.00e+00 4.39e+03]]
4391
[[   0. 4391.]]
[[   0. 4391.]]
[[   0. 4391.]]
[[   0. 4391.]]
[[1.000e+00 4.391e+03]]
[[   0. 4391.]]
[[   0. 4391.]]
[[   0. 4391.]]
[[2.000e+00 4.391e+03]]
4392
[[   0. 4392.]]
[[   0. 4392.]]
[[   0. 4392.]]
[[   0. 4392.]]
[[1.000e+00 4.392e+03]]
[[   0. 4392.]]
[[   0. 4392.]]
[[   0. 4392.]]
4393
[[   0. 4393.]]
[[   0. 4393.]]
[[   0. 4393.]]
[[   0. 4393.]]
[[1.000e+00 4.393e+03]]
[[2.000e+00 4.393e+03]]
[[2.000e+00 4.393e+03]]
[[2.000e+00 4.393e+03]]
4394
[[   0. 4394.]]
[[   0. 4394.]]
[[   0. 4394.]]
[[   0. 4394.]]
[[1.000e+00 4.394e+03]]
[[2.000e+00 4.394e+03]]
[[2.000e+00 4.394e+03]]
4395
[[   0. 4395.]]
[[   0. 4395.]]
[[   0. 4395.]]
[[   0. 4395.]]
[[1.000e+00 4.395e+03]]


[[   0. 4447.]]
[[   0. 4447.]]
[[   0. 4447.]]
[[   0. 4447.]]
[[1.000e+00 4.447e+03]]
[[   0. 4447.]]
[[1.000e+00 4.447e+03]]
4448
[[   0. 4448.]]
[[   0. 4448.]]
[[   0. 4448.]]
[[   0. 4448.]]
[[1.000e+00 4.448e+03]]
[[   0. 4448.]]
[[   0. 4448.]]
[[   0. 4448.]]
4449
[[   0. 4449.]]
[[   0. 4449.]]
[[   0. 4449.]]
[[   0. 4449.]]
[[1.000e+00 4.449e+03]]
[[2.000e+00 4.449e+03]]
[[2.000e+00 4.449e+03]]
4450
[[   0. 4450.]]
[[   0. 4450.]]
[[   0. 4450.]]
[[   0. 4450.]]
[[1.00e+00 4.45e+03]]
[[1.00e+00 4.45e+03]]
4451
[[   0. 4451.]]
[[   0. 4451.]]
[[   0. 4451.]]
[[   0. 4451.]]
[[   0. 4451.]]
[[   0. 4451.]]
[[   0. 4451.]]
[[2.000e+00 4.451e+03]]
4452
[[   0. 4452.]]
[[   0. 4452.]]
[[   0. 4452.]]
[[   0. 4452.]]
[[   0. 4452.]]
[[   0. 4452.]]
[[   0. 4452.]]
4453
[[   0. 4453.]]
[[   0. 4453.]]
[[   0. 4453.]]
[[   0. 4453.]]
[[2.000e+00 4.453e+03]]
[[2.000e+00 4.453e+03]]
[[2.000e+00 4.453e+03]]
4454
[[   0. 4454.]]
[[   0. 4454.]]
[[   0. 4454.]]
[[   0. 4454.]]
[[2.000e+

[[   0. 4528.]]
[[   0. 4528.]]
[[   0. 4528.]]
[[   0. 4528.]]
[[   0. 4528.]]
4529
[[   0. 4529.]]
[[   0. 4529.]]
[[   0. 4529.]]
[[   0. 4529.]]
[[2.000e+00 4.529e+03]]
[[   0. 4529.]]
4530
[[   0. 4530.]]
[[   0. 4530.]]
[[   0. 4530.]]
[[   0. 4530.]]
[[2.00e+00 4.53e+03]]
4531
[[   0. 4531.]]
[[   0. 4531.]]
[[   0. 4531.]]
[[   0. 4531.]]
[[   0. 4531.]]
4532
[[   0. 4532.]]
[[   0. 4532.]]
[[   0. 4532.]]
[[   0. 4532.]]
4533
[[2.000e+00 4.533e+03]]
[[2.000e+00 4.533e+03]]
[[   0. 4533.]]
[[   0. 4533.]]
[[2.000e+00 4.533e+03]]
[[   0. 4533.]]
4534
[[2.000e+00 4.534e+03]]
[[2.000e+00 4.534e+03]]
[[   0. 4534.]]
[[   0. 4534.]]
[[2.000e+00 4.534e+03]]
4535
[[2.000e+00 4.535e+03]]
[[2.000e+00 4.535e+03]]
[[   0. 4535.]]
[[   0. 4535.]]
[[   0. 4535.]]
4536
[[2.000e+00 4.536e+03]]
[[2.000e+00 4.536e+03]]
[[   0. 4536.]]
[[   0. 4536.]]
4537
[[2.000e+00 4.537e+03]]
[[2.000e+00 4.537e+03]]
[[   0. 4537.]]
[[2.000e+00 4.537e+03]]
[[   0. 4537.]]
4538
[[2.000e+00 4.538e+03]]
[[2.000e

[[   0. 4624.]]
[[   0. 4624.]]
[[2.000e+00 4.624e+03]]
[[   0. 4624.]]
[[   0. 4624.]]
4625
[[   0. 4625.]]
[[   0. 4625.]]
[[   0. 4625.]]
[[   0. 4625.]]
[[2.000e+00 4.625e+03]]
[[   0. 4625.]]
4626
[[   0. 4626.]]
[[   0. 4626.]]
[[   0. 4626.]]
[[   0. 4626.]]
[[   0. 4626.]]
[[   0. 4626.]]
4627
[[   0. 4627.]]
[[   0. 4627.]]
[[   0. 4627.]]
[[   0. 4627.]]
[[   0. 4627.]]
4628
[[2.000e+00 4.628e+03]]
[[2.000e+00 4.628e+03]]
[[   0. 4628.]]
[[2.000e+00 4.628e+03]]
[[   0. 4628.]]
[[   0. 4628.]]
4629
[[2.000e+00 4.629e+03]]
[[2.000e+00 4.629e+03]]
[[   0. 4629.]]
[[2.000e+00 4.629e+03]]
[[   0. 4629.]]
4630
[[2.00e+00 4.63e+03]]
[[2.00e+00 4.63e+03]]
[[   0. 4630.]]
[[   0. 4630.]]
[[   0. 4630.]]
4631
[[2.000e+00 4.631e+03]]
[[2.000e+00 4.631e+03]]
[[   0. 4631.]]
[[   0. 4631.]]
4632
[[1.000e+00 4.632e+03]]
[[   0. 4632.]]
[[2.000e+00 4.632e+03]]
[[   0. 4632.]]
[[   0. 4632.]]
4633
[[1.000e+00 4.633e+03]]
[[   0. 4633.]]
[[2.000e+00 4.633e+03]]
[[   0. 4633.]]
4634
[[1.000e+0

[[2.000e+00 4.692e+03]]
[[2.000e+00 4.692e+03]]
[[   0. 4692.]]
[[   0. 4692.]]
[[1.000e+00 4.692e+03]]
[[   0. 4692.]]
4693
[[1.000e+00 4.693e+03]]
[[   0. 4693.]]
[[   0. 4693.]]
[[   0. 4693.]]
[[1.000e+00 4.693e+03]]
[[   0. 4693.]]
[[2.000e+00 4.693e+03]]
4694
[[1.000e+00 4.694e+03]]
[[   0. 4694.]]
[[   0. 4694.]]
[[1.000e+00 4.694e+03]]
[[   0. 4694.]]
[[2.000e+00 4.694e+03]]
4695
[[1.000e+00 4.695e+03]]
[[   0. 4695.]]
[[   0. 4695.]]
[[1.000e+00 4.695e+03]]
[[   0. 4695.]]
4696
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
[[   0. 4696.]]
4697
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
[[   0. 4697.]]
4698
[[   0. 4698.]]
[[   0. 4698.]]
[[   0. 4698.]]
[[   0. 4698.]]
[[   0. 4698.]]
[[   0. 4698.]]
[[   0. 4698.]]
[[1.000e+00 4.698e+03]]
[[   0. 4698.]]
4699
[[   

[[   0. 4760.]]
[[   0. 4760.]]
[[   0. 4760.]]
[[   0. 4760.]]
[[   0. 4760.]]
[[   0. 4760.]]
4761
[[   0. 4761.]]
[[   0. 4761.]]
[[   0. 4761.]]
[[2.000e+00 4.761e+03]]
[[   0. 4761.]]
[[2.000e+00 4.761e+03]]
4762
[[   0. 4762.]]
[[   0. 4762.]]
[[   0. 4762.]]
[[2.000e+00 4.762e+03]]
[[   0. 4762.]]
[[2.000e+00 4.762e+03]]
4763
[[   0. 4763.]]
[[   0. 4763.]]
[[   0. 4763.]]
[[2.000e+00 4.763e+03]]
[[   0. 4763.]]
4764
[[   0. 4764.]]
[[   0. 4764.]]
[[   0. 4764.]]
[[   0. 4764.]]
[[2.000e+00 4.764e+03]]
[[2.000e+00 4.764e+03]]
4765
[[   0. 4765.]]
[[   0. 4765.]]
[[   0. 4765.]]
[[   0. 4765.]]
[[2.000e+00 4.765e+03]]
4766
[[   0. 4766.]]
[[   0. 4766.]]
[[   0. 4766.]]
[[   0. 4766.]]
[[2.000e+00 4.766e+03]]
4767
[[   0. 4767.]]
[[   0. 4767.]]
[[   0. 4767.]]
[[   0. 4767.]]
4768
[[1.000e+00 4.768e+03]]
[[   0. 4768.]]
[[   0. 4768.]]
[[   0. 4768.]]
[[2.000e+00 4.768e+03]]
[[2.000e+00 4.768e+03]]
4769
[[1.000e+00 4.769e+03]]
[[   0. 4769.]]
[[   0. 4769.]]
[[   0. 4769.]]
[[2

[[   0. 4828.]]
[[   0. 4828.]]
[[   0. 4828.]]
[[   0. 4828.]]
[[   0. 4828.]]
[[   0. 4828.]]
[[   0. 4828.]]
[[1.000e+00 4.828e+03]]
4829
[[   0. 4829.]]
[[   0. 4829.]]
[[   0. 4829.]]
[[   0. 4829.]]
[[   0. 4829.]]
[[   0. 4829.]]
[[   0. 4829.]]
[[   0. 4829.]]
[[   0. 4829.]]
4830
[[   0. 4830.]]
[[   0. 4830.]]
[[   0. 4830.]]
[[   0. 4830.]]
[[   0. 4830.]]
[[   0. 4830.]]
[[2.00e+00 4.83e+03]]
[[2.00e+00 4.83e+03]]
4831
[[   0. 4831.]]
[[   0. 4831.]]
[[   0. 4831.]]
[[   0. 4831.]]
[[   0. 4831.]]
[[   0. 4831.]]
[[1.000e+00 4.831e+03]]
4832
[[   0. 4832.]]
[[   0. 4832.]]
[[   0. 4832.]]
[[   0. 4832.]]
[[   0. 4832.]]
[[   0. 4832.]]
[[   0. 4832.]]
[[   0. 4832.]]
[[   0. 4832.]]
4833
[[   0. 4833.]]
[[   0. 4833.]]
[[   0. 4833.]]
[[   0. 4833.]]
[[   0. 4833.]]
[[   0. 4833.]]
[[2.000e+00 4.833e+03]]
[[2.000e+00 4.833e+03]]
4834
[[   0. 4834.]]
[[   0. 4834.]]
[[   0. 4834.]]
[[   0. 4834.]]
[[   0. 4834.]]
[[   0. 4834.]]
[[1.000e+00 4.834e+03]]
4835
[[   0. 4835.]]
[

[[   0. 4911.]]
[[   0. 4911.]]
[[   0. 4911.]]
[[   0. 4911.]]
4912
[[   0. 4912.]]
[[   0. 4912.]]
[[   0. 4912.]]
[[   0. 4912.]]
4913
[[   0. 4913.]]
[[   0. 4913.]]
[[   0. 4913.]]
[[   0. 4913.]]
4914
[[   0. 4914.]]
[[   0. 4914.]]
[[   0. 4914.]]
4915
[[   0. 4915.]]
[[   0. 4915.]]
[[   0. 4915.]]
[[   0. 4915.]]
4916
[[   0. 4916.]]
[[   0. 4916.]]
[[   0. 4916.]]
4917
[[   0. 4917.]]
[[   0. 4917.]]
[[   0. 4917.]]
[[   0. 4917.]]
[[   0. 4917.]]
[[   0. 4917.]]
[[2.000e+00 4.917e+03]]
[[2.000e+00 4.917e+03]]
[[   0. 4917.]]
[[2.000e+00 4.917e+03]]
4918
[[   0. 4918.]]
[[   0. 4918.]]
[[   0. 4918.]]
[[   0. 4918.]]
[[   0. 4918.]]
[[   0. 4918.]]
[[2.000e+00 4.918e+03]]
[[2.000e+00 4.918e+03]]
[[   0. 4918.]]
4919
[[   0. 4919.]]
[[   0. 4919.]]
[[   0. 4919.]]
[[   0. 4919.]]
[[   0. 4919.]]
[[   0. 4919.]]
[[1.000e+00 4.919e+03]]
[[   0. 4919.]]
[[2.000e+00 4.919e+03]]
4920
[[   0. 4920.]]
[[   0. 4920.]]
[[   0. 4920.]]
[[2.00e+00 4.92e+03]]
[[2.00e+00 4.92e+03]]
[[2.00e

[[   0. 4967.]]
[[   0. 4967.]]
[[   0. 4967.]]
[[1.000e+00 4.967e+03]]
[[   0. 4967.]]
[[   0. 4967.]]
[[1.000e+00 4.967e+03]]
4968
[[   0. 4968.]]
[[   0. 4968.]]
[[   0. 4968.]]
[[1.000e+00 4.968e+03]]
[[   0. 4968.]]
[[   0. 4968.]]
[[   0. 4968.]]
[[   0. 4968.]]
4969
[[   0. 4969.]]
[[   0. 4969.]]
[[   0. 4969.]]
[[1.000e+00 4.969e+03]]
[[   0. 4969.]]
[[1.000e+00 4.969e+03]]
4970
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
[[   0. 4970.]]
4971
[[   0. 4971.]]
[[   0. 4971.]]
[[   0. 4971.]]
[[   0. 4971.]]
[[   0. 4971.]]
[[   0. 4971.]]
[[   0. 4971.]]
[[   0. 4971.]]
[[2.000e+00 4.971e+03]]
[[2.000e+00 4.971e+03]]
4972
[[   0. 4972.]]
[[   0. 4972.]]
[[   0. 4972.]]
[[   0. 4972.]]
[[   0. 4972.]]
[[   0. 4972.]]
[[   0. 4972.]]
[[   0. 4972.]]
[[1.000e+00 4.972e+03]]
4973
[[   0. 4973.]]
[[   0. 4973.]]
[[   0. 4973.]]
[[   0. 4973.]]
[[   0. 4973.]]
[[2.000e+0

0

In [ ]:
           if countH[j] > 0:
                if connected_positions[j][0] < connected_positions[j][1]:
                    connected_positions[j][0] = connected_positions[j][0]
                else:
                    connected_positions[j][0] = connected_positions[j][1]
           
            carbon_position = connected_positions[j][0]        

            
            if group[j] == 2.0:
                countC1 = np.zeros((len(connected_positions)))
                countO1 = np.zeros((len(connected_positions)))
                countH1 = np.zeros((len(connected_positions)))
                countN1 = np.zeros((len(connected_positions)))
                carbon_neighbor_connections = neighboring_connections(name_mol,carbon_position,number_atoms)
                for i in range(len(carbon_neighbor_connections)):
                    countxyzlines = 0
                    for line2 in fileinput.FileInput(name_xyz,inplace=0):
                        countxyzlines = countxyzlines + 1
                        if countxyzlines == carbon_neighbor_connections[i] + 2:
                            if 'C ' in line2:
                                countC1[j] = countC1[j] + 1
                            if 'H ' in line2:
                                countH1[j] = countH1[j] + 1
                            if 'N ' in line2:
                                countN1[j] = countN1[j] + 1
                            if 'O ' in line2:
                                countO1[j] = countO1[j] +1
                
                if countH1[j] == 2 and countC1[j] == 0:
                    label[j] = 2
                elif countC1[j] == 1 and countO1[j] ==1 and countH1[j] > 0 and countN1[j] ==0:
                    label[j] = 2
                elif countC1[j] == 2:
                    label[j] = 3
                elif countO1[j] > 1:
                    label[j] = 4
                elif countN1[j] > 0:
                    label[j] = 5
                else:
                    label[j] = 6
                
            
            
        
            if group[j] == 1.0:
                countC2 = np.zeros((len(connected_positions)))
                countH2 = np.zeros((len(connected_positions)))
                countO2 = np.zeros((len(connected_positions)))
                countN2 = np.zeros((len(connected_positions)))
                carbon_neighbor_connections = neighboring_connections(name_mol,carbon_position,number_atoms)
                for i in range(len(carbon_neighbor_connections)):
                    countxyzlines = 0
                    for line2 in fileinput.FileInput(name_xyz,inplace=0):
                        countxyzlines = countxyzlines + 1
                        if countxyzlines == carbon_neighbor_connections[i] + 2:
                            if 'C ' in line2:
                                countC2[j] = countC2[j] + 1
                            if 'H ' in line2:
                                countH2[j] = countH2[j] + 1
                            if 'N ' in line2:
                                countN2[j] = countN2[j] + 1
                            if 'O ' in line2:
                                countO2[j] = countO2[j] + 1
                if countC[j] == 0:
                    label[j] = 7
                elif countC2[j] + countN2[j] + countO2[j] == 2:
                    label[j] = 7
                elif countH2[j] == 2 or countH2[j] == 3:  
                    label[j]=7
                elif countC2[j] + countN2[j] + countO2[j] == 3:
                    label[j] = 8
                elif countC2[j] + countN2[j] + countO2[j] == 4:
                    label[j] = 9
                else:
                    label[j] = 6
                print(countC2[j])
                print(countH2[j])
                print(countN2[j])
                print(countO2[j])
                print(label[j])
                
                