In [6]:
### #Loads the best_model after schnet training.
#user evaluates the model on the QM9 database

import schnetpack as spk
import torch
import schnetpack.nn 
import schnetpack.data
from schnetpack.datasets import QM9

from ase.io import read
import numpy as np
from numpy import genfromtxt, savetxt
# Load best model where it was stored after training

model = torch.load("../../../data/trained_models/qm9_i6_30f_10000_5000/best_model", map_location=torch.device('cpu'))

# Download QM9 dataset to use in evaluating model
qm9data = QM9('./qm9.db', download=True, remove_uncharacterized=True)

# Load split file 
train, val, test = spk.data.train_test_split(qm9data, split_file='../../../data/trained_models/qm9_i6_30f_10000_5000/split.npz')


device = 'cpu'

calculator = spk.interfaces.SpkCalculator(model=model, device=device, energy=QM9.U0)
converter = spk.data.AtomsConverter(device=device)
# load data for molecule
at, props = qm9data.get_properties(13)

# set calculator on molecule
at.set_calculator(calculator)

# convert qm9 data to machine-readable form
inputs = converter(at)


pred = model(inputs)

print('Prediction:', pred[QM9.U0].detach().cpu().numpy()[0,0])
print('Keys:', list(inputs.keys()))
print('Truth:', props[QM9.U0].cpu().numpy()[0])

from schnetpack.atomistic.output_modules import yi
from schnetpack.atomistic.output_modules import y0
from schnetpack.representation.schnet import x0
from schnetpack.representation.schnet import x

print(yi)


x = x.detach().numpy()
print(x[0][8])
z = np.zeros(30)
for i in range(30):
    z[i] = x[0][8][i]


Prediction: -4217.3306
Keys: ['_atomic_numbers', '_positions', '_cell', '_neighbors', '_cell_offset', '_atom_mask', '_neighbor_mask', 'representation']
Truth: -4217.023
tensor([[[-1033.5311],
         [-1033.5496],
         [-2046.5616],
         [  -17.3803],
         [  -17.3803],
         [  -17.3479],
         [  -17.3185],
         [  -17.3185],
         [  -16.9430]]], grad_fn=<AddBackward0>)
[ 0.873716    0.72314894  2.2314045  -1.055411    1.7409477   1.6494476
  2.4670506   5.095903    0.14799182 -7.002657    1.331481   -1.3886635
  0.16347688  1.3694193  -3.5233307  -2.7108958   1.5107887   0.5807687
 -0.0275597   2.9418695  -0.08728649  1.9064639  -0.9612253  -2.9872088
  1.1584371   1.1594511   3.0716043   0.03464839 -1.2672491  -0.67741585]


In [72]:
### #Loads the best_model after schnet training.
#user evaluates the model on the QM9 database

import schnetpack as spk
import torch
import schnetpack.nn 
import schnetpack.data
from schnetpack.datasets import QM9

from ase.io import read
import numpy as np
# Load best model where it was stored after training

model = torch.load("../../../data/trained_models/qm9_i6_30f_10000_5000/best_model", map_location=torch.device('cpu'))

# Download QM9 dataset to use in evaluating model
qm9data = QM9('./qm9.db', download=True, remove_uncharacterized=True)

# Load split file 
train, val, test = spk.data.train_test_split(qm9data, split_file='../../../data/trained_models/qm9_i6_30f_10000_5000/split.npz')


device = 'cpu'

atoms = read('../../../data/single-shot/etoh-dis2.xyz')

converter = spk.data.AtomsConverter(device=device)
inputs = converter(atoms)

pred = model(inputs)

print('Prediction:', pred[QM9.U0].detach().cpu().numpy()[0,0])

from schnetpack.atomistic.output_modules import yi
from schnetpack.atomistic.output_modules import y0
from schnetpack.representation.schnet import x0
from schnetpack.representation.schnet import x

print(yi)

x = x.detach().numpy()
print(x[0][8])
z = np.zeros(30)
for i in range(30):
    z[i] = x[0][8][i]

print(z)

Prediction: -4218.53
tensor([[[-1033.5732],
         [-1033.5774],
         [-2047.0161],
         [  -17.4733],
         [  -17.3658],
         [  -17.3889],
         [  -17.3889],
         [  -17.3728],
         [  -17.3728]]], grad_fn=<AddBackward0>)
[-0.51658505  1.8643203   0.71664757  0.33644342  2.7771304  -0.43251517
  1.260131    2.0335727   0.99730337 -4.217264   -0.29221678 -1.1096499
 -1.1510872  -1.4722742   0.8835117  -2.3961847   0.08462888  0.49352393
  0.37247065 -0.43126577  0.28620416  0.05957144  0.9291179   0.1323758
  1.1483123  -1.3055406  -0.7718257  -0.4072759   0.31449732 -1.0546603 ]
[-0.51658505  1.86432028  0.71664757  0.33644342  2.77713037 -0.43251517
  1.260131    2.03357267  0.99730337 -4.21726418 -0.29221678 -1.1096499
 -1.15108716 -1.47227418  0.88351172 -2.39618468  0.08462888  0.49352393
  0.37247065 -0.43126577  0.28620416  0.05957144  0.92911792  0.13237581
  1.14831233 -1.30554056 -0.77182567 -0.40727589  0.31449732 -1.05466032]


In [73]:
### #Loads the best_model after schnet training.
#user evaluates the model on the QM9 database

import schnetpack as spk
import torch
import schnetpack.nn 
import schnetpack.data
from schnetpack.datasets import QM9

from ase.io import read
import numpy as np
# Load best model where it was stored after training

model = torch.load("../../../data/trained_models/qm9_i6_30f_10000_5000/best_model", map_location=torch.device('cpu'))

# Download QM9 dataset to use in evaluating model
qm9data = QM9('./qm9.db', download=True, remove_uncharacterized=True)

# Load split file 
train, val, test = spk.data.train_test_split(qm9data, split_file='../../../data/trained_models/qm9_i6_30f_10000_5000/split.npz')


device = 'cpu'

atoms = read('../../../data/single-shot/etoh-dis3.xyz')

converter = spk.data.AtomsConverter(device=device)
inputs = converter(atoms)

pred = model(inputs)

print('Prediction:', pred[QM9.U0].detach().cpu().numpy()[0,0])

from schnetpack.atomistic.output_modules import yi
from schnetpack.atomistic.output_modules import y0
from schnetpack.representation.schnet import x0
from schnetpack.representation.schnet import x

print(yi)


x = x.detach().numpy()
print(x[0][8])
z = np.zeros(30)
for i in range(30):
    z[i] = x[0][8][i]
    
print(z)

Prediction: -4218.53
tensor([[[-1033.5732],
         [-1033.5774],
         [-2047.0161],
         [  -17.4733],
         [  -17.3658],
         [  -17.3889],
         [  -17.3889],
         [  -17.3728],
         [  -17.3728]]], grad_fn=<AddBackward0>)
[-0.51658505  1.8643203   0.71664757  0.33644342  2.7771304  -0.43251517
  1.260131    2.0335727   0.99730337 -4.217264   -0.29221678 -1.1096499
 -1.1510872  -1.4722742   0.8835117  -2.3961847   0.08462888  0.49352393
  0.37247065 -0.43126577  0.28620416  0.05957144  0.9291179   0.1323758
  1.1483123  -1.3055406  -0.7718257  -0.4072759   0.31449732 -1.0546603 ]
[-0.51658505  1.86432028  0.71664757  0.33644342  2.77713037 -0.43251517
  1.260131    2.03357267  0.99730337 -4.21726418 -0.29221678 -1.1096499
 -1.15108716 -1.47227418  0.88351172 -2.39618468  0.08462888  0.49352393
  0.37247065 -0.43126577  0.28620416  0.05957144  0.92911792  0.13237581
  1.14831233 -1.30554056 -0.77182567 -0.40727589  0.31449732 -1.05466032]


In [74]:
### #Loads the best_model after schnet training.
#user evaluates the model on the QM9 database

import schnetpack as spk
import torch
import schnetpack.nn 
import schnetpack.data
from schnetpack.datasets import QM9

from ase.io import read
import numpy as np
# Load best model where it was stored after training

model = torch.load("../../../data/trained_models/qm9_i6_30f_10000_5000/best_model", map_location=torch.device('cpu'))

# Download QM9 dataset to use in evaluating model
qm9data = QM9('./qm9.db', download=True, remove_uncharacterized=True)

# Load split file 
train, val, test = spk.data.train_test_split(qm9data, split_file='../../../data/trained_models/qm9_i6_30f_10000_5000/split.npz')


device = 'cpu'

atoms = read('../../../data/single-shot/etoh-dis4.xyz')

converter = spk.data.AtomsConverter(device=device)
inputs = converter(atoms)

pred = model(inputs)

print('Prediction:', pred[QM9.U0].detach().cpu().numpy()[0,0])

from schnetpack.atomistic.output_modules import yi
from schnetpack.atomistic.output_modules import y0
from schnetpack.representation.schnet import x0
from schnetpack.representation.schnet import x

print(yi)


print(x)

Prediction: -4218.53
tensor([[[-1033.5732],
         [-1033.5774],
         [-2047.0161],
         [  -17.4733],
         [  -17.3658],
         [  -17.3889],
         [  -17.3889],
         [  -17.3728],
         [  -17.3728]]], grad_fn=<AddBackward0>)
tensor([[[-1.3468,  1.0117,  0.6345, -0.0378,  2.9618, -1.5334, -0.9348,
           4.1826,  1.4608, -4.7305,  0.8645, -1.7537, -1.5458, -0.1885,
          -2.6309, -2.6601, -0.6184,  0.3064, -1.4664,  0.6776,  0.0819,
           0.8442, -0.5064, -2.5298, -0.7821,  0.9581, -2.2033, -1.5046,
          -0.2412, -2.7409],
         [-0.5243,  2.5019,  0.4180, -0.4041,  2.2111, -1.2708,  0.0385,
           2.8952, -0.3822, -5.6090,  0.9585, -1.7383, -2.9014, -0.8800,
          -2.1035, -2.8596,  2.5515,  0.0191, -1.0353,  2.0375,  1.3390,
           1.3576, -0.4864,  0.3206, -0.1298,  0.2384, -1.8484, -0.6027,
          -1.0986, -2.0047],
         [ 1.3959, -0.8670,  0.1407,  0.6849,  0.0681, -0.3361,  1.1854,
          -2.4867, -2.6070, -0.

In [ ]:
### #Loads the best_model after schnet training.
#user evaluates the model on the QM9 database

import schnetpack as spk
import torch
import schnetpack.nn 
import schnetpack.data
from schnetpack.datasets import QM9

from ase.io import read
import numpy as np
# Load best model where it was stored after training

model = torch.load("../../../data/trained_models/qm9_i6_30f_10000_5000/best_model", map_location=torch.device('cpu'))

# Download QM9 dataset to use in evaluating model
qm9data = QM9('./qm9.db', download=True, remove_uncharacterized=True)

# Load split file 
train, val, test = spk.data.train_test_split(qm9data, split_file='../../../data/trained_models/qm9_i6_30f_10000_5000/split.npz')


device = 'cpu'

atoms = read('../../../data/single-shot/etoh-dis5.xyz')

converter = spk.data.AtomsConverter(device=device)
inputs = converter(atoms)

pred = model(inputs)

print('Prediction:', pred[QM9.U0].detach().cpu().numpy()[0,0])

from schnetpack.atomistic.output_modules import yi
from schnetpack.atomistic.output_modules import y0
from schnetpack.representation.schnet import x0
from schnetpack.representation.schnet import x

print(yi)


print(x)

In [75]:
from schnetpack.datasets import QM9
        
at, props = qm9data.get_properties(13)    

# convert qm9 data to machine-readable form
inputs = converter(at)

calculator = spk.interfaces.SpkCalculator(model=model, device=device, energy=QM9.U0)
at.set_calculator(calculator)

pred = model(inputs)
from schnetpack.representation.schnet import x0
from schnetpack.atomistic.output_modules import yi

from schnetpack.representation.schnet import v

print(yi)
print(v)

print('Prediction:', pred[QM9.U0].detach().cpu().numpy()[0,0])

tensor([[[-1033.5311],
         [-1033.5496],
         [-2046.5616],
         [  -17.3803],
         [  -17.3803],
         [  -17.3479],
         [  -17.3185],
         [  -17.3185],
         [  -16.9430]]], grad_fn=<AddBackward0>)
tensor([[[-2.0070e-02, -1.2018e-01, -4.8509e-01, -3.3334e-01, -3.2861e-01,
           2.4058e-01, -5.4608e-01, -4.3546e-02,  3.6813e-01, -5.6585e-01,
           2.1026e-01, -8.2096e-01, -4.2437e-01, -3.1172e-01,  1.2935e-01,
           9.8918e-03, -4.4588e-01, -6.6941e-04, -2.1074e-01, -1.8167e-01,
           5.7560e-01, -3.8204e-01, -3.9405e-01, -4.4155e-01,  1.1846e-01,
           3.0199e-01, -4.7728e-01,  1.0010e-01, -8.9314e-02, -2.0802e-01],
         [ 3.3703e-01, -1.0521e+00, -1.3421e+00, -1.7541e-01, -1.3550e-01,
           3.0121e-02, -8.1325e-01, -7.9196e-01,  4.2789e-01,  1.6062e-02,
           1.1511e+00, -1.3611e+00, -5.3497e-01,  1.3626e-01,  6.5030e-01,
           3.2648e-01,  1.1300e+00, -8.6349e-01,  9.0586e-01, -8.3910e-01,
          -1.147