In [142]:
import numpy as np

i = -np.ones((1,1), dtype=np.float32)
print(i)

[[-1.]]


In [143]:
n = 5

i = np.tile(np.arange(n, dtype=np.float32)[np.newaxis], (n,1))

print(i)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [144]:
# ~np.eye deletes all diagonal elements and squishes to 1D array
# for atomic systems, this can be used to represent that all atoms are neighbors 
# but of course not neighbors to themselves (delete diagonals) and reshape

i = i[~np.eye(n,dtype=np.bool)].reshape(n,n-1)
print(i)

[[1. 2. 3. 4.]
 [0. 2. 3. 4.]
 [0. 1. 3. 4.]
 [0. 1. 2. 4.]
 [0. 1. 2. 3.]]


In [145]:
## np.array When creating multidimensional arrays note the square brackets! 

grid = np.array([[1,2,3],[1,2,3]])
print(grid)
print(grid.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [146]:
# np.hstack, stack a column to the right
# np.vstack, stack a row at the bottom
i = np.hstack([i, -np.ones((n,1))])
print(i)

[[ 1.  2.  3.  4. -1.]
 [ 0.  2.  3.  4. -1.]
 [ 0.  1.  3.  4. -1.]
 [ 0.  1.  2.  4. -1.]
 [ 0.  1.  2.  3. -1.]]


In [141]:
## grid
